import type { MunicipalityId } from "./location-area";

export type Village = { id: string; ka: string; en: string };

const V = (id: string, ka: string, en: string): Village => ({ id, ka, en });

export const MUNICIPALITY_VILLAGES: Record<MunicipalityId, readonly Village[]> = {
  // ── Samegrelo-Zemo Svaneti ──
  abasha: [
    V("abasha", "აბაშა", "Abasha"),
    V("dzveli-abasha", "ძველი აბაშა", "Dzveli Abasha"),
    V("gezati", "გეზათი", "Gezati"),
    V("ketilari", "კეტილარი", "Ketilari"),
    V("kolobani", "კოლობანი", "Kolobani"),
    V("marani", "მარანი", "Marani"),
    V("naesakovo", "ნაესაკოვო", "Naesakovo"),
    V("norio", "ნორიო", "Norio"),
    V("ontopo", "ონტოპო", "Ontopo"),
    V("pirveli-maisi", "პირველი მაისი", "Pirveli Maisi"),
    V("samikao", "სამიკაო", "Samikao"),
    V("sepieti", "სეპიეთი", "Sepieti"),
    V("sujuna", "სუჯუნა", "Sujuna"),
    V("tkviri", "ტყვირი", "Tkviri"),
    V("tsqemi", "წყემი", "Tsqemi"),
    V("zanati", "ზანათი", "Zanati")
  ],
  martvili: [
    V("martvili", "მარტვილი", "Martvili"),
    V("abedati", "აბედათი", "Abedati"),
    V("bandza", "ბანძა", "Bandza"),
    V("gachedili", "გაჭედილი", "Gachedili"),
    V("didi-chkoni", "დიდი ჭყონი", "Didi Chkoni"),
    V("gurdzemi", "გურძემი", "Gurdzemi"),
    V("inchkhuri", "ინჩხური", "Inchkhuri"),
    V("khuntsi", "ხუნწი", "Khuntsi"),
    V("kurzu", "კურზუ", "Kurzu"),
    V("lekhaindrao", "ლეხაინდრაო", "Lekhaindrao"),
    V("nakhunao", "ნახუნაო", "Nakhunao"),
    V("onoghia", "ონოღია", "Onoghia"),
    V("pirveli-balda", "პირველი ბალდა", "Pirveli Balda"),
    V("meore-balda", "მეორე ბალდა", "Meore Balda"),
    V("mesame-balda", "მესამე ბალდა", "Mesame Balda"),
    V("salkhino", "სალხინო", "Salkhino"),
    V("sergieti", "სერგიეთი", "Sergieti"),
    V("tamakoni", "თამაკონი", "Tamakoni")
  ],
  senaki: [
    V("senaki", "სენაკი", "Senaki"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-senaki", "ძველი სენაკი", "Dzveli Senaki"),
    V("eki", "ეკი", "Eki"),
    V("gejeti", "გეჯეთი", "Gejeti"),
    V("khorshi", "ხორში", "Khorshi"),
    V("ledzadzame", "ლეძაძამე", "Ledzadzame"),
    V("menji", "მენჯი", "Menji"),
    V("nokalakevi", "ნოკალაკევი", "Nokalakevi"),
    V("nosiri", "ნოსირი", "Nosiri"),
    V("potshkho", "ფოცხო", "Potshkho"),
    V("teklati", "თეკლათი", "Teklati"),
    V("ushapati", "უშაპათი", "Ushapati"),
    V("zani", "ზანი", "Zani"),
    V("zemo-chaladidi", "ზემო ჭალადიდი", "Zemo Chaladidi")
  ],
  chokhorotsku: [
    V("chokhorotsku", "ჩხოროწყუ", "Chokhorotsku"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("anaklia", "ანაკლია", "Anaklia"),
    V("dzveli-chkhorotsku", "ძველი ჩხოროწყუ", "Dzveli Chkhorotsku"),
    V("gantiadi", "განთიადი", "Gantiadi"),
    V("grigoleti", "გრიგოლეთი", "Grigoleti"),
    V("kakhati", "კახათი", "Kakhati"),
    V("kokoleti", "კოკოლეთი", "Kokoleti"),
    V("kulevi", "კულევი", "Kulevi"),
    V("maltakva", "მალთაყვა", "Maltakva"),
    V("mekhadidzhiri", "მეხადიჯირი", "Mekhadidzhiri"),
    V("natanebi", "ნატანები", "Natanebi"),
    V("ochamchire", "ოჩამჩირე", "Ochamchire"),
    V("pichori", "ფიჭორი", "Pichori")
  ],
  khobi: [
    V("khobi", "ხობი", "Khobi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("anaklia", "ანაკლია", "Anaklia"),
    V("dzveli-khobi", "ძველი ხობი", "Dzveli Khobi"),
    V("gantiadi", "განთიადი", "Gantiadi"),
    V("grigoleti", "გრიგოლეთი", "Grigoleti"),
    V("kokoleti", "კოკოლეთი", "Kokoleti"),
    V("kulevi", "კულევი", "Kulevi"),
    V("maltakva", "მალთაყვა", "Maltakva"),
    V("mekhadidzhiri", "მეხადიჯირი", "Mekhadidzhiri"),
    V("natanebi", "ნატანები", "Natanebi"),
    V("pichori", "ფიჭორი", "Pichori")
  ],
  tsalenjikha: [
    V("tsalenjikha", "წალენჯიხჰა", "Tsalenjikha"),
    V("chale", "ჩალე", "Chale"),
    V("dzveli-tsalenjikha", "ძველი წალენჯიხჰა", "Dzveli Tsalenjikha"),
    V("jvari", "ჯვარი", "Jvari"),
    V("khviteri", "ხვიტერი", "Khviteri"),
    V("kheta", "ქეთა", "Kheta"),
    V("khevi", "ხევი", "Khevi"),
    V("lebarde", "ლებარდე", "Lebarde"),
    V("lia", "ლია", "Lia"),
    V("mikava", "მიქავა", "Mikava"),
    V("mukhuri", "მუხური", "Mukhuri"),
    V("muzhava", "მუჟავა", "Muzhava"),
    V("nakhakhulevi", "ნახახულევი", "Nakhakhulevi"),
    V("obuji", "ობუჯი", "Obuji"),
    V("shua-kheta", "შუა ქეთა", "Shua Kheta")
  ],
  lentekhi: [
    V("lentekhi", "ლენტეხი", "Lentekhi"),
    V("alphouti", "ალფაუთი", "Alpouti"),
    V("askhi", "ასხი", "Askhi"),
    V("choluri", "ჭოლური", "Choluri"),
    V("ghebi", "ღები", "Ghebi"),
    V("khe", "ხე", "Khe"),
    V("matskhvarishi", "მაცხვარიში", "Matskhvarishi"),
    V("oni", "ონი", "Oni"),
    V("utsera", "უწერა", "Utsera"),
    V("zeda-lentekhi", "ზედა ლენტეხი", "Zeda Lentekhi")
  ],
  mestia: [
    V("mestia", "მესტია", "Mestia"),
    V("becho", "ბეჩო", "Becho"),
    V("chuberi", "ჩაბერი", "Chuberi"),
    V("etseri", "ეწერი", "Etseri"),
    V("hatsvali", "ჰაწვალი", "Hatsvali"),
    V("ieli", "იელი", "Ieli"),
    V("kala", "კალა", "Kala"),
    V("latali", "ლათალი", "Latali"),
    V("lenjeri", "ლენჯერი", "Lenjeri"),
    V("mulakhi", "მულახი", "Mulakhi"),
    V("nakra", "ნაკრა", "Nakra"),
    V("tamarasheni", "თამარაშენი", "Tamarasheni"),
    V("tviberi", "თვიბერი", "Tviberi"),
    V("ushguli", "უშგული", "Ushguli"),
    V("zeda-mestia", "ზედა მესტია", "Zeda Mestia")
  ],
  tsageri: [
    V("tsageri", "წაგერი", "Tsageri"),
    V("alphouti", "ალფაუთი", "Alpouti"),
    V("choluri", "ჭოლური", "Choluri"),
    V("ghebi", "ღები", "Ghebi"),
    V("khe", "ხე", "Khe"),
    V("matskhvarishi", "მაცხვარიში", "Matskhvarishi"),
    V("oni", "ონი", "Oni"),
    V("utsera", "უწერა", "Utsera"),
    V("zeda-tsageri", "ზედა წაგერი", "Zeda Tsageri"),
    V("lechkhumi", "ლეჩხუმი", "Lechkhumi")
  ],

  // ── Imereti ──
  kharagauli: [
    V("kharagauli", "ხარაგაული", "Kharagauli"),
    V("argveta", "არგვეთი", "Argveta"),
    V("dzveli-kharagauli", "ძველი ხარაგაული", "Dzveli Kharagauli"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("mukhrani", "მუხრანი", "Mukhrani"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-kharagauli", "პატარა ხარაგაული", "Patara Kharagauli"),
    V("shrosha", "შროშა", "Shrosha"),
    V("sviri", "სვირი", "Sviri"),
    V("terjili", "ტერჯილი", "Terjili"),
    V("kulbaki", "კულბაკი", "Kulbaki"),
    V("sazano", "საზანო", "Sazano"),
    V("zeda-kharagauli", "ზედა ხარაგაული", "Zeda Kharagauli")
  ],
  khoni: [
    V("khoni", "ხონი", "Khoni"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-khoni", "ძველი ხონი", "Dzveli Khoni"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-khoni", "პატარა ხონი", "Patara Khoni"),
    V("shrosha", "შროშა", "Shrosha"),
    V("sviri", "სვირი", "Sviri"),
    V("zeda-khoni", "ზედა ხონი", "Zeda Khoni"),
    V("gordi", "გორდი", "Gordi"),
    V("khidistavi", "ხიდისთავი", "Khidistavi"),
    V("sachkhere", "საჩხერე", "Sachkhere")
  ],
  sachkhere: [
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("argveta", "არგვეთი", "Argveta"),
    V("dzveli-sachkhere", "ძველი საჩხერე", "Dzveli Sachkhere"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-sachkhere", "პატარა საჩხერე", "Patara Sachkhere"),
    V("shrosha", "შროშა", "Shrosha"),
    V("sviri", "სვირი", "Sviri"),
    V("zeda-sachkhere", "ზედა საჩხერე", "Zeda Sachkhere"),
    V("jikhaishi", "ჯიხაიში", "Jikhaishi"),
    V("sviri-gorge", "სვირის ხეობა", "Sviri Gorge")
  ],
  tkibuli: [
    V("tkibuli", "ყიბული", "Tkibuli"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-tkibuli", "ძველი ყიბული", "Dzveli Tkibuli"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-tkibuli", "პატარა ყიბული", "Patara Tkibuli"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-tkibuli", "ზედა ყიბული", "Zeda Tkibuli"),
    V("mghvimevi", "მღვიმევი", "Mghvimevi"),
    V("katskhi", "კაღხი", "Katskhi"),
    V("sachkhere", "საჩხერე", "Sachkhere")
  ],
  tskaltubo: [
    V("tskaltubo", "წყალტუბო", "Tskaltubo"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-tskaltubo", "ძველი წყალტუბო", "Dzveli Tskaltubo"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-tskaltubo", "პატარა წყალტუბო", "Patara Tskaltubo"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-tskaltubo", "ზედა წყალტუბო", "Zeda Tskaltubo"),
    V("gumbra", "გუმბრა", "Gumbra"),
    V("kopitnari", "კოპიტნარი", "Kopitnari"),
    V("patara-satsire", "პატარა საცირე", "Patara Satsire")
  ],
  terjola: [
    V("terjola", "ყერჯოლა", "Terjola"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-terjola", "ძველი ყერჯოლა", "Dzveli Terjola"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-terjola", "პატარა ყერჯოლა", "Patara Terjola"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-terjola", "ზედა ყერჯოლა", "Zeda Terjola"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("vani", "ვანი", "Vani"),
    V("gvitoria", "გვიტორია", "Gvitoria")
  ],
  vani: [
    V("vani", "ვანი", "Vani"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-vani", "ძველი ვანი", "Dzveli Vani"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-vani", "პატარა ვანი", "Patara Vani"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-vani", "ზედა ვანი", "Zeda Vani"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("gvitoria", "გვიტორია", "Gvitoria"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  chiatura: [
    V("chiatura", "ჭიატურა", "Chiatura"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-chiatura", "ძველი ჭიატურა", "Dzveli Chiatura"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-chiatura", "პატარა ჭიატურა", "Patara Chiatura"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-chiatura", "ზედა ჭიატურა", "Zeda Chiatura"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("tkibuli", "ყიბული", "Tkibuli"),
    V("mghvimevi", "მღვიმევი", "Mghvimevi")
  ],
  baghdati: [
    V("baghdati", "ბაგდათი", "Baghdati"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-baghdati", "ძველი ბაგდათი", "Dzveli Baghdati"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-baghdati", "პატარა ბაგდათი", "Patara Baghdati"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-baghdati", "ზედა ბაგდათი", "Zeda Baghdati"),
    V("vani", "ვანი", "Vani"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("gvitoria", "გვიტორია", "Gvitoria")
  ],
  zestaponi: [
    V("zestaponi", "ზესტაფონი", "Zestaponi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-zestaponi", "ძველი ზესტაფონი", "Dzveli Zestaponi"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-zestaponi", "პატარა ზესტაფონი", "Patara Zestaponi"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-zestaponi", "ზედა ზესტაფონი", "Zeda Zestaponi"),
    V("vani", "ვანი", "Vani"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("gvitoria", "გვიტორია", "Gvitoria")
  ],
  samtredia: [
    V("samtredia", "სამტრედია", "Samtredia"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-samtredia", "ძველი სამტრედია", "Dzveli Samtredia"),
    V("gveta", "გვეთა", "Gveta"),
    V("khevi", "ხევი", "Khevi"),
    V("nigozeti", "ნიგოზეთი", "Nigozeti"),
    V("patara-samtredia", "პატარა სამტრედია", "Patara Samtredia"),
    V("shrosha", "შროშა", "Shrosha"),
    V("zeda-samtredia", "ზედა სამტრედია", "Zeda Samtredia"),
    V("vani", "ვანი", "Vani"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("gvitoria", "გვიტორია", "Gvitoria")
  ],

  // ── Adjara ──
  kobuleti: [
    V("kobuleti", "ქობულეთი", "Kobuleti"),
    V("chakvi", "ჭაკვი", "Chakvi"),
    V("dzveli-kobuleti", "ძველი ქობულეთი", "Dzveli Kobuleti"),
    V("gantiadi", "განტიადი", "Gantiadi"),
    V("grigoleti", "გრიგოლეთი", "Grigoleti"),
    V("kakhati", "კახათი", "Kakhati"),
    V("kokoleti", "კოკოლეთი", "Kokoleti"),
    V("kulevi", "კულევი", "Kulevi"),
    V("maltakva", "მალტაყვა", "Maltakva"),
    V("mekhadidzhiri", "მეხადიჯირი", "Mekhadidzhiri"),
    V("natanebi", "ნატანები", "Natanebi"),
    V("pichori", "ფიჭორი", "Pichori"),
    V("tsikhisdziri", "წიხისძირი", "Tsikhisdziri"),
    V("chanieti", "ჩანიეთი", "Chanieti")
  ],
  "khelvachauri-city": [
    V("khelvachauri", "ხელვაჩაური", "Khelvachauri"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("chakvi", "ჭაკვი", "Chakvi"),
    V("dzveli-khelvachauri", "ძველი ხელვაჩაური", "Dzveli Khelvachauri"),
    V("gantiadi", "განტიადი", "Gantiadi"),
    V("grigoleti", "გრიგოლეთი", "Grigoleti"),
    V("kakhati", "კახათი", "Kakhati"),
    V("kokoleti", "კოკოლეთი", "Kokoleti"),
    V("kulevi", "კულევი", "Kulevi"),
    V("maltakva", "მალტაყვა", "Maltakva"),
    V("mekhadidzhiri", "მეხადიჯირი", "Mekhadidzhiri"),
    V("natanebi", "ნატანები", "Natanebi"),
    V("pichori", "ფიჭორი", "Pichori")
  ],
  keda: [
    V("keda", "კედა", "Keda"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-keda", "ძველი კედა", "Dzveli Keda"),
    V("gomi", "გომი", "Gomi"),
    V("khinotsminda", "ხინოცმინდა", "Khinotsminda"),
    V("merisi", "მერისი", "Merisi"),
    V("mtisubani", "მტისუბანი", "Mtisubani"),
    V("namonastrevi", "ნამონასტრევი", "Namonastrevi"),
    V("peria", "პერია", "Peria"),
    V("shua-keda", "შუა კედა", "Shua Keda"),
    V("zeda-keda", "ზედა კედა", "Zeda Keda"),
    V("zemo-keda", "ზემო კედა", "Zemo Keda")
  ],
  shuakhevi: [
    V("shuakhevi", "შუახევი", "Shuakhevi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-shuakhevi", "ძველი შუახევი", "Dzveli Shuakhevi"),
    V("gomi", "გომი", "Gomi"),
    V("khinotsminda", "ხინოცმინდა", "Khinotsminda"),
    V("merisi", "მერისი", "Merisi"),
    V("mtisubani", "მტისუბანი", "Mtisubani"),
    V("namonastrevi", "ნამონასტრევი", "Namonastrevi"),
    V("peria", "პერია", "Peria"),
    V("shua-shuakhevi", "შუა შუახევი", "Shua Shuakhevi"),
    V("zeda-shuakhevi", "ზედა შუახევი", "Zeda Shuakhevi"),
    V("zemo-shuakhevi", "ზემო შუახევი", "Zemo Shuakhevi")
  ],
  khulo: [
    V("khulo", "ხულო", "Khulo"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-khulo", "ძველი ხულო", "Dzveli Khulo"),
    V("gomi", "გომი", "Gomi"),
    V("khinotsminda", "ხინოცმინდა", "Khinotsminda"),
    V("merisi", "მერისი", "Merisi"),
    V("mtisubani", "მტისუბანი", "Mtisubani"),
    V("namonastrevi", "ნამონასტრევი", "Namonastrevi"),
    V("peria", "პერია", "Peria"),
    V("shua-khulo", "შუა ხულო", "Shua Khulo"),
    V("zeda-khulo", "ზედა ხულო", "Zeda Khulo"),
    V("zemo-khulo", "ზემო ხულო", "Zemo Khulo")
  ],

  // ── Guria ──
  ozurgeti: [
    V("ozurgeti", "ოზურგეთი", "Ozurgeti"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-ozurgeti", "ძველი ოზურგეთი", "Dzveli Ozurgeti"),
    V("bakhvi", "ბახვი", "Bakhvi"),
    V("gomi", "გომი", "Gomi"),
    V("likhauri", "ლიხაური", "Likhauri"),
    V("makhuntseti", "მახუნღეთი", "Makhuntseti"),
    V("naruja", "ნარუჯა", "Naruja"),
    V("vakijvari", "ვაკიჯვარი", "Vakijvari"),
    V("zeda-ozurgeti", "ზედა ოზურგეთი", "Zeda Ozurgeti"),
    V("zemo-ozurgeti", "ზემო ოზურგეთი", "Zemo Ozurgeti"),
    V("chanieti", "ჩანიეთი", "Chanieti")
  ],
  lanchkhuti: [
    V("lanchkhuti", "ლანჩხუთი", "Lanchkhuti"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-lanchkhuti", "ძველი ლანჩხუთი", "Dzveli Lanchkhuti"),
    V("bakhvi", "ბახვი", "Bakhvi"),
    V("gomi", "გომი", "Gomi"),
    V("likhauri", "ლიხაური", "Likhauri"),
    V("makhuntseti", "მახუნღეთი", "Makhuntseti"),
    V("naruja", "ნარუჯა", "Naruja"),
    V("vakijvari", "ვაკიჯვარი", "Vakijvari"),
    V("zeda-lanchkhuti", "ზედა ლანჩხუთი", "Zeda Lanchkhuti"),
    V("zemo-lanchkhuti", "ზემო ლანჩხუთი", "Zemo Lanchkhuti"),
    V("chanieti", "ჩანიეთი", "Chanieti")
  ],
  chokhatauri: [
    V("chokhatauri", "ჩოხატაური", "Chokhatauri"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-chokhatauri", "ძველი ჩოხატაური", "Dzveli Chokhatauri"),
    V("bakhvi", "ბახვი", "Bakhvi"),
    V("gomi", "გომი", "Gomi"),
    V("likhauri", "ლიხაური", "Likhauri"),
    V("makhuntseti", "მახუნღეთი", "Makhuntseti"),
    V("naruja", "ნარუჯა", "Naruja"),
    V("vakijvari", "ვაკიჯვარი", "Vakijvari"),
    V("zeda-chokhatauri", "ზედა ჩოხატაური", "Zeda Chokhatauri"),
    V("zemo-chokhatauri", "ზემო ჩოხატაური", "Zemo Chokhatauri"),
    V("chanieti", "ჩანიეთი", "Chanieti")
  ],

  // ── Samtskhe-Javakheti ──
  akhaltsikhe: [
    V("akhaltsikhe", "ახალციხე", "Akhaltsikhe"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-akhaltsikhe", "ძველი ახალციხე", "Dzveli Akhaltsikhe"),
    V("abastumani", "აბასტუმანი", "Abastumani"),
    V("akhalkalaki", "ახალკალაკი", "Akhalkalaki"),
    V("aspindza", "ასფინძა", "Aspindza"),
    V("borjomi", "ბორჟომი", "Borjomi"),
    V("vardzia", "ვარძია", "Vardzia"),
    V("tmogvi", "ტმოგვი", "Tmogvi"),
    V("khertvisi", "ხერტვისი", "Khertvisi"),
    V("zeda-akhaltsikhe", "ზედა ახალციხე", "Zeda Akhaltsikhe"),
    V("zemo-akhaltsikhe", "ზემო ახალციხე", "Zemo Akhaltsikhe")
  ],
  adigeni: [
    V("adigeni", "ადიგენი", "Adigeni"),
    V("abastumani", "აბასტუმანი", "Abastumani"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-adigeni", "ძველი ადიგენი", "Dzveli Adigeni"),
    V("gomareti", "გომარეთი", "Gomareti"),
    V("kvabiskhevi", "კვაბისხევი", "Kvabiskhevi"),
    V("nijgori", "ნიჯგორი", "Nijgori"),
    V("phlate", "ფლატე", "Phlate"),
    V("samsari", "სამსარი", "Samsari"),
    V("sapara", "საფარა", "Sapara"),
    V("ude", "უდე", "Ude"),
    V("zeda-adigeni", "ზედა ადიგენი", "Zeda Adigeni")
  ],
  aspindza: [
    V("aspindza", "ასფინძა", "Aspindza"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-aspindza", "ძველი ასფინძა", "Dzveli Aspindza"),
    V("khertvisi", "ხერტვისი", "Khertvisi"),
    V("tmogvi", "ტმოგვი", "Tmogvi"),
    V("vardzia", "ვარძია", "Vardzia"),
    V("zeda-aspindza", "ზედა ასფინძა", "Zeda Aspindza"),
    V("zemo-aspindza", "ზემო ასფინძა", "Zemo Aspindza"),
    V("akhaltsikhe", "ახალციხე", "Akhaltsikhe"),
    V("adigeni", "ადიგენი", "Adigeni"),
    V("borjomi", "ბორჟომი", "Borjomi"),
    V("ninotsminda", "ნინოცმინდა", "Ninotsminda")
  ],
  akhalkalaki: [
    V("akhalkalaki", "ახალკალაკი", "Akhalkalaki"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-akhalkalaki", "ძველი ახალკალაკი", "Dzveli Akhalkalaki"),
    V("baraleti", "ბარალეთი", "Baraleti"),
    V("bugasheni", "ბუგაშენი", "Bugasheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("moghrani", "მოღრანი", "Moghrani"),
    V("samsari", "სამსარი", "Samsari"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("troitskoe", "ტროიცკოე", "Troitskoe"),
    V("zeda-akhalkalaki", "ზედა ახალკალაკი", "Zeda Akhalkalaki"),
    V("zemo-akhalkalaki", "ზემო ახალკალაკი", "Zemo Akhalkalaki")
  ],
  ninotsminda: [
    V("ninotsminda", "ნინოცმინდა", "Ninotsminda"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-ninotsminda", "ძველი ნინოცმინდა", "Dzveli Ninotsminda"),
    V("baraleti", "ბარალეთი", "Baraleti"),
    V("bugasheni", "ბუგაშენი", "Bugasheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("moghrani", "მოღრანი", "Moghrani"),
    V("samsari", "სამსარი", "Samsari"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("zeda-ninotsminda", "ზედა ნინოცმინდა", "Zeda Ninotsminda"),
    V("zemo-ninotsminda", "ზემო ნინოცმინდა", "Zemo Ninotsminda"),
    V("akhalkalaki", "ახალკალაკი", "Akhalkalaki")
  ],
  tsalka: [
    V("tsalka", "ცალკა", "Tsalka"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-tsalka", "ძველი ცალკა", "Dzveli Tsalka"),
    V("baraleti", "ბარალეთი", "Baraleti"),
    V("bugasheni", "ბუგაშენი", "Bugasheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("moghrani", "მოღრანი", "Moghrani"),
    V("samsari", "სამსარი", "Samsari"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("zeda-tsalka", "ზედა ცალკა", "Zeda Tsalka"),
    V("zemo-tsalka", "ზემო ცალკა", "Zemo Tsalka"),
    V("akhalkalaki", "ახალკალაკი", "Akhalkalaki")
  ],
  borjomi: [
    V("borjomi", "ბორჟომი", "Borjomi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-borjomi", "ძველი ბორჟომი", "Dzveli Borjomi"),
    V("abastumani", "აბასტუმანი", "Abastumani"),
    V("akhaltsikhe", "ახალციხე", "Akhaltsikhe"),
    V("aspindza", "ასფინძა", "Aspindza"),
    V("likani", "ლიკანი", "Likani"),
    V("timotesubani", "ტიმოტესუბანი", "Timotesubani"),
    V("zeda-borjomi", "ზედა ბორჟომი", "Zeda Borjomi"),
    V("zemo-borjomi", "ზემო ბორჟომი", "Zemo Borjomi"),
    V("adigeni", "ადიგენი", "Adigeni"),
    V("khertvisi", "ხერტვისი", "Khertvisi")
  ],

  // ── Kvemo Kartli ──
  marneuli: [
    V("marneuli", "მარნეული", "Marneuli"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-marneuli", "ძველი მარნეული", "Dzveli Marneuli"),
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("tetritskaro", "ტეტრიღკარო", "Tetritskaro"),
    V("kaspi", "კასფი", "Kaspi"),
    V("zeda-marneuli", "ზედა მარნეული", "Zeda Marneuli"),
    V("zemo-marneuli", "ზემო მარნეული", "Zemo Marneuli"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  gardabani: [
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-gardabani", "ძველი გარდაბანი", "Dzveli Gardabani"),
    V("marneuli", "მარნეული", "Marneuli"),
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("tetritskaro", "ტეტრიღკარო", "Tetritskaro"),
    V("kaspi", "კასფი", "Kaspi"),
    V("zeda-gardabani", "ზედა გარდაბანი", "Zeda Gardabani"),
    V("zemo-gardabani", "ზემო გარდაბანი", "Zemo Gardabani"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  bolnisi: [
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-bolnisi", "ძველი ბოლნისი", "Dzveli Bolnisi"),
    V("marneuli", "მარნეული", "Marneuli"),
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("tetritskaro", "ტეტრიღკარო", "Tetritskaro"),
    V("kaspi", "კასფი", "Kaspi"),
    V("zeda-bolnisi", "ზედა ბოლნისი", "Zeda Bolnisi"),
    V("zemo-bolnisi", "ზემო ბოლნისი", "Zemo Bolnisi"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  dmanisi: [
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-dmanisi", "ძველი დმანისი", "Dzveli Dmanisi"),
    V("marneuli", "მარნეული", "Marneuli"),
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("tetritskaro", "ტეტრიღკარო", "Tetritskaro"),
    V("kaspi", "კასფი", "Kaspi"),
    V("zeda-dmanisi", "ზედა დმანისი", "Zeda Dmanisi"),
    V("zemo-dmanisi", "ზემო დმანისი", "Zemo Dmanisi"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  tetritskaro: [
    V("tetritskaro", "ტეტრიღკარო", "Tetritskaro"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-tetritskaro", "ძველი ტეტრიღკარო", "Dzveli Tetritskaro"),
    V("marneuli", "მარნეული", "Marneuli"),
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("kaspi", "კასფი", "Kaspi"),
    V("zeda-tetritskaro", "ზედა ტეტრიღკარო", "Zeda Tetritskaro"),
    V("zemo-tetritskaro", "ზემო ტეტრიღკარო", "Zemo Tetritskaro"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  kaspi: [
    V("kaspi", "კასფი", "Kaspi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-kaspi", "ძველი კასფი", "Dzveli Kaspi"),
    V("marneuli", "მარნეული", "Marneuli"),
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("tetritskaro", "ტეტრიღკარო", "Tetritskaro"),
    V("zeda-kaspi", "ზედა კასფი", "Zeda Kaspi"),
    V("zemo-kaspi", "ზემო კასფი", "Zemo Kaspi"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],

  // ── Shida Kartli ──
  khashuri: [
    V("khashuri", "ხაშური", "Khashuri"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-khashuri", "ძველი ხაშური", "Dzveli Khashuri"),
    V("borjomi", "ბორჟომი", "Borjomi"),
    V("kharagauli", "ხარაგაული", "Kharagauli"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("zeda-khashuri", "ზედა ხაშური", "Zeda Khashuri"),
    V("zemo-khashuri", "ზემო ხაშური", "Zemo Khashuri"),
    V("surami", "სურამი", "Surami"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("jikhaishi", "ჯიხაიში", "Jikhaishi")
  ],
  akhalgori: [
    V("akhalgori", "ახალგორი", "Akhalgori"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-akhalgori", "ძველი ახალგორი", "Dzveli Akhalgori"),
    V("khashuri", "ხაშური", "Khashuri"),
    V("mtskheta", "მღხეთა", "Mtskheta"),
    V("dusheti", "დუშეთი", "Dusheti"),
    V("tianeti", "ტიანეთი", "Tianeti"),
    V("akhmeta", "ახმეტა", "Akhmeta"),
    V("zeda-akhalgori", "ზედა ახალგორი", "Zeda Akhalgori"),
    V("zemo-akhalgori", "ზემო ახალგორი", "Zemo Akhalgori"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],

  // ── Mtskheta-Mtianeti ──
  mtskheta: [
    V("mtskheta", "მღხეთა", "Mtskheta"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-mtskheta", "ძველი მღხეთა", "Dzveli Mtskheta"),
    V("dusheti", "დუშეთი", "Dusheti"),
    V("tianeti", "ტიანეთი", "Tianeti"),
    V("akhmeta", "ახმეტა", "Akhmeta"),
    V("akhalgori", "ახალგორი", "Akhalgori"),
    V("zeda-mtskheta", "ზედა მღხეთა", "Zeda Mtskheta"),
    V("zemo-mtskheta", "ზემო მღხეთა", "Zemo Mtskheta"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("jvari", "ჯვარი", "Jvari")
  ],
  dusheti: [
    V("dusheti", "დუშეთი", "Dusheti"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-dusheti", "ძველი დუშეთი", "Dzveli Dusheti"),
    V("mtskheta", "მღხეთა", "Mtskheta"),
    V("tianeti", "ტიანეთი", "Tianeti"),
    V("akhmeta", "ახმეტა", "Akhmeta"),
    V("akhalgori", "ახალგორი", "Akhalgori"),
    V("zeda-dusheti", "ზედა დუშეთი", "Zeda Dusheti"),
    V("zemo-dusheti", "ზემო დუშეთი", "Zemo Dusheti"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("jvari", "ჯვარი", "Jvari")
  ],
  tianeti: [
    V("tianeti", "ტიანეთი", "Tianeti"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-tianeti", "ძველი ტიანეთი", "Dzveli Tianeti"),
    V("mtskheta", "მღხეთა", "Mtskheta"),
    V("dusheti", "დუშეთი", "Dusheti"),
    V("akhmeta", "ახმეტა", "Akhmeta"),
    V("akhalgori", "ახალგორი", "Akhalgori"),
    V("zeda-tianeti", "ზედა ტიანეთი", "Zeda Tianeti"),
    V("zemo-tianeti", "ზემო ტიანეთი", "Zemo Tianeti"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("jvari", "ჯვარი", "Jvari")
  ],
  akhmeta: [
    V("akhmeta", "ახმეტა", "Akhmeta"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-akhmeta", "ძველი ახმეტა", "Dzveli Akhmeta"),
    V("mtskheta", "მღხეთა", "Mtskheta"),
    V("dusheti", "დუშეთი", "Dusheti"),
    V("tianeti", "ტიანეთი", "Tianeti"),
    V("akhalgori", "ახალგორი", "Akhalgori"),
    V("zeda-akhmeta", "ზედა ახმეტა", "Zeda Akhmeta"),
    V("zemo-akhmeta", "ზემო ახმეტა", "Zemo Akhmeta"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("jvari", "ჯვარი", "Jvari")
  ],

  // ── Kakheti ──
  telavi: [
    V("telavi", "ტელავი", "Telavi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-telavi", "ძველი ტელავი", "Dzveli Telavi"),
    V("gurjaani", "გურჟაანი", "Gurjaani"),
    V("sagarejo", "საგარეჯო", "Sagarejo"),
    V("signagi", "სიგნაგი", "Signagi"),
    V("lagodekhi", "ლაგოდეხი", "Lagodekhi"),
    V("dedoplistskaro", "დედოფლისღყარო", "Dedoplistskaro"),
    V("zeda-telavi", "ზედა ტელავი", "Zeda Telavi"),
    V("zemo-telavi", "ზემო ტელავი", "Zemo Telavi"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  gurjaani: [
    V("gurjaani", "გურჟაანი", "Gurjaani"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-gurjaani", "ძველი გურჟაანი", "Dzveli Gurjaani"),
    V("telavi", "ტელავი", "Telavi"),
    V("sagarejo", "საგარეჯო", "Sagarejo"),
    V("signagi", "სიგნაგი", "Signagi"),
    V("lagodekhi", "ლაგოდეხი", "Lagodekhi"),
    V("dedoplistskaro", "დედოფლისღყარო", "Dedoplistskaro"),
    V("zeda-gurjaani", "ზედა გურჟაანი", "Zeda Gurjaani"),
    V("zemo-gurjaani", "ზემო გურჟაანი", "Zemo Gurjaani"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  sagarejo: [
    V("sagarejo", "საგარეჯო", "Sagarejo"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-sagarejo", "ძველი საგარეჯო", "Dzveli Sagarejo"),
    V("telavi", "ტელავი", "Telavi"),
    V("gurjaani", "გურჟაანი", "Gurjaani"),
    V("signagi", "სიგნაგი", "Signagi"),
    V("lagodekhi", "ლაგოდეხი", "Lagodekhi"),
    V("dedoplistskaro", "დედოფლისღყარო", "Dedoplistskaro"),
    V("zeda-sagarejo", "ზედა საგარეჯო", "Zeda Sagarejo"),
    V("zemo-sagarejo", "ზემო საგარეჯო", "Zemo Sagarejo"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  signagi: [
    V("signagi", "სიგნაგი", "Signagi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-signagi", "ძველი სიგნაგი", "Dzveli Signagi"),
    V("telavi", "ტელავი", "Telavi"),
    V("gurjaani", "გურჟაანი", "Gurjaani"),
    V("sagarejo", "საგარეჯო", "Sagarejo"),
    V("lagodekhi", "ლაგოდეხი", "Lagodekhi"),
    V("dedoplistskaro", "დედოფლისღყარო", "Dedoplistskaro"),
    V("zeda-signagi", "ზედა სიგნაგი", "Zeda Signagi"),
    V("zemo-signagi", "ზემო სიგნაგი", "Zemo Signagi"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  lagodekhi: [
    V("lagodekhi", "ლაგოდეხი", "Lagodekhi"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-lagodekhi", "ძველი ლაგოდეხი", "Dzveli Lagodekhi"),
    V("telavi", "ტელავი", "Telavi"),
    V("gurjaani", "გურჟაანი", "Gurjaani"),
    V("sagarejo", "საგარეჯო", "Sagarejo"),
    V("signagi", "სიგნაგი", "Signagi"),
    V("dedoplistskaro", "დედოფლისღყარო", "Dedoplistskaro"),
    V("zeda-lagodekhi", "ზედა ლაგოდეხი", "Zeda Lagodekhi"),
    V("zemo-lagodekhi", "ზემო ლაგოდეხი", "Zemo Lagodekhi"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],
  dedoplistskaro: [
    V("dedoplistskaro", "დედოფლისღყარო", "Dedoplistskaro"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-dedoplistskaro", "ძველი დედოფლისღყარო", "Dzveli Dedoplistskaro"),
    V("telavi", "ტელავი", "Telavi"),
    V("gurjaani", "გურჟაანი", "Gurjaani"),
    V("sagarejo", "საგარეჯო", "Sagarejo"),
    V("signagi", "სიგნაგი", "Signagi"),
    V("lagodekhi", "ლაგოდეხი", "Lagodekhi"),
    V("zeda-dedoplistskaro", "ზედა დედოფლისღყარო", "Zeda Dedoplistskaro"),
    V("zemo-dedoplistskaro", "ზემო დედოფლისღყარო", "Zemo Dedoplistskaro"),
    V("satskheni", "საცხენი", "Satskheni"),
    V("kumurdo", "კუმურდო", "Kumurdo")
  ],

  // ── Racha-Lechkhumi-Kvemo Svaneti ──
  ambrolauri: [
    V("ambrolauri", "ამბროლაური", "Ambrolauri"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("dzveli-ambrolauri", "ძველი ამბროლაური", "Dzveli Ambrolauri"),
    V("alpana", "ალფანა", "Alpana"),
    V("bagebi", "ბაგები", "Bagebi"),
    V("ghebi", "ღები", "Ghebi"),
    V("khvanchkara", "ხვანჩკარა", "Khvanchkara"),
    V("nakuruli", "ნაკურული", "Nakuruli"),
    V("saori", "საორი", "Saori"),
    V("tsageri", "წაგერი", "Tsageri"),
    V("utsera", "უწერა", "Utsera"),
    V("zeda-ambrolauri", "ზედა ამბროლაური", "Zeda Ambrolauri")
  ],

};

export function getVillagesForMunicipality(
  municipality: string,
): readonly Village[] {
  if (municipality in MUNICIPALITY_VILLAGES) {
    return MUNICIPALITY_VILLAGES[municipality as MunicipalityId];
  }
  return [];
}

export function getVillageLabel(
  villages: readonly Village[],
  id: string,
  locale: "ka" | "en",
): string {
  const village = villages.find((v) => v.id === id);
  if (!village) return id;
  return locale === "ka" ? village.ka : village.en;
}
