import type { MunicipalityId } from "./location-area";

export type Village = { id: string; ka: string; en: string };

const V = (id: string, ka: string, en: string): Village => ({ id, ka, en });

export const MUNICIPALITY_VILLAGES: Record<MunicipalityId, readonly Village[]> = {
  gori: [
    V("avchala", "ავჭალა", "Avchala"),
    V("agara", "აგარა", "Agara"),
    V("alaverdi", "ალავერდი", "Alaverdi"),
    V("andriatsminda", "ანდრიაწმინდა", "Andriatsminda"),
    V("arbo", "არბო", "Arbo"),
    V("arashenda", "არაშენდა", "Arashenda"),
    V("aragvispiri", "არაგვისპირი", "Aragvispiri"),
    V("ateni", "ატენი", "Ateni"),
    V("akhaldaba", "ახალდაბა", "Akhaldaba"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("berbuki", "ბერბუკი", "Berbuki"),
    V("boshuri", "ბოშური", "Boshuri"),
    V("bershueti", "ბერშუეთი", "Bershueti"),
    V("bozhami", "ბოჟამი", "Bozhami"),
    V("gantiadi", "განთიადი", "Gantiadi"),
    V("garejvari", "გარეჯვარი", "Garejvari"),
    V("gorijvari", "გორიჯვარი", "Gorijvari"),
    V("grakali", "გრაკალი", "Grakali"),
    V("gugtiantkari", "გუგტიანთკარი", "Gugtiantkari"),
    V("dvani", "დვანი", "Dvani"),
    V("ditsi", "დიცი", "Ditsi"),
    V("doesi", "დოესი", "Doesi"),
    V("eredvi", "ერედვი", "Eredvi"),
    V("variani", "ვარიანი", "Variani"),
    V("zemo-nikozi", "ზემო ნიქოზი", "Zemo Nikozi"),
    V("tavtsqaro", "თავწყარო", "Tavtsqaro"),
    V("karaleti", "კარალეთი", "Karaleti"),
    V("kirbali", "კირბალი", "Kirbali"),
    V("kvarkhiti", "კვარხითი", "Kvarkhiti"),
    V("kodistsqaro", "კოდისწყარო", "Kodistsqaro"),
    V("korinta", "კორინთა", "Korinta"),
    V("kere", "ქერე", "Kere"),
    V("kvemo-nikozi", "ქვემო ნიქოზი", "Kvemo Nikozi"),
    V("kvemo-rekha", "ქვემო რეხა", "Kvemo Rekha"),
    V("mejvriskhevi", "მეჯვრისხევი", "Mejvriskhevi"),
    V("mikhailovka", "მიხაილოვკა", "Mikhailovka"),
    V("morgeti", "მორგეთი", "Morgeti"),
    V("mkhetseti", "მხეცეთი", "Mkhetseti"),
    V("nkhvrebeti", "ნხვრებეთი", "Nkhvrebeti"),
    V("ormotsi", "ორმოცი", "Ormotsi"),
    V("pivnisi", "პივნისი", "Pivnisi"),
    V("romiani", "რომიანი", "Romiani"),
    V("satsverali", "საწვერალი", "Satsverali"),
    V("sveneti", "სვენეთი", "Sveneti"),
    V("tqviavi", "ტყვიავი", "Tqviavi"),
    V("kitsnisi", "ქიწნისი", "Kitsnisi"),
    V("shavshvebi", "შავშვები", "Shavshvebi"),
    V("shindisi", "შინდისი", "Shindisi"),
    V("dzevera", "ძევერა", "Dzevera"),
    V("tsedisi", "წედისი", "Tsedisi"),
    V("tsirkvali", "წირქვალი", "Tsirkvali"),
    V("charebuli", "ჭარებული", "Charebuli"),
    V("khidistavi", "ხიდისთავი", "Khidistavi"),
    V("jariasheni", "ჯარიაშენი", "Jariasheni"),
  ],
  zugdidi: [
    V("abastumani", "აბასთუმანი", "Abastumani"),
    V("alkunja", "ალკუნჯა", "Alkunja"),
    V("akhalabastumani", "ახალაბასთუმანი", "Akhalabastumani"),
    V("akhalkoda", "ახალკოდა", "Akhalkoda"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("ganmukhuri", "განმუხური", "Ganmukhuri"),
    V("grada", "გრადა", "Grada"),
    V("dadianeti", "დადიანეთი", "Dadianeti"),
    V("didi-nedzi", "დიდი ნეძი", "Didi Nedzi"),
    V("ergeta", "ერგეტა", "Ergeta"),
    V("zana", "ზანა", "Zana"),
    V("kakhati", "კახათი", "Kakhati"),
    V("koka", "კოკა", "Koka"),
    V("kortskheli", "კორცხელი", "Kortskheli"),
    V("letsulei", "ლეწულეი", "Letsulei"),
    V("mikeleponi", "მიქელეფონი", "Mikeleponi"),
    V("mukhura", "მუხურა", "Mukhura"),
    V("narazeni", "ნარაზენი", "Narazeni"),
    V("orsantia", "ორსანტია", "Orsantia"),
    V("odishi", "ოდიში", "Odishi"),
    V("patara-nedzi", "პატარა ნეძი", "Patara Nedzi"),
    V("zhoneti", "ჟონეთი", "Zhoneti"),
    V("rukhi", "რუხი", "Rukhi"),
    V("riqe", "რიყე", "Riqe"),
    V("savane", "სავანე", "Savane"),
    V("samsonovi", "სამსონოვი", "Samsonovi"),
    V("sataplia", "სათაფლია", "Sataplia"),
    V("jikhashkari", "ჯიხაშკარი", "Jikhashkari"),
    V("chkhoria", "ჩხორია", "Chkhoria"),
    V("tsatskhvi", "ცაცხვი", "Tsatskhvi"),
    V("chitatsqari", "ჭითაწყარი", "Chitatsqari"),
    V("chaladidi", "ჭალადიდი", "Chaladidi"),
    V("khetsera", "ხეცერა", "Khetsera"),
    V("jumiti", "ჯუმითი", "Jumiti"),
  ],
  abasha: [
    V("abasha", "აბაშა", "Abasha"),
    V("bulachauri", "ბულაჩაური", "Bulachauri"),
    V("gezeti", "გეზეთი", "Gezeti"),
    V("gaghma-etseri", "გაღმა ეწერი", "Gaghma Etseri"),
    V("gulmagari", "გულმაგარი", "Gulmagari"),
    V("dapnari", "დაფნარი", "Dapnari"),
    V("zanati", "ზანათი", "Zanati"),
    V("ketilari", "კეთილარი", "Ketilari"),
    V("marani", "მარანი", "Marani"),
    V("martvili", "მარტვილი", "Martvili"),
    V("naesakavo", "ნაესაკავო", "Naesakavo"),
    V("nosiri", "ნოსირი", "Nosiri"),
    V("sabulavo", "საბულავო", "Sabulavo"),
    V("sagvazavo", "საგვაზავო", "Sagvazavo"),
    V("sapiratsia", "საპირაცია", "Sapiratsia"),
    V("sujuna", "სუჯუნა", "Sujuna"),
    V("tqviavi", "ტყვიავი", "Tqviavi"),
    V("kolobani", "ქოლობანი", "Kolobani"),
    V("dzveli-abasha", "ძველი აბაშა", "Dzveli Abasha"),
    V("tsqemi", "წყემი", "Tsqemi"),
    V("chaladidi", "ჭალადიდი", "Chaladidi"),
  ],
  adigeni: [
    V("abastumani", "აბასთუმანი", "Abastumani"),
    V("adigeni", "ადიგენი", "Adigeni"),
    V("araleti", "არალეთი", "Araleti"),
    V("bolachuri", "ბოლაჩური", "Bolachuri"),
    V("varkhani", "ვარხანი", "Varkhani"),
    V("zarzma", "ზარზმა", "Zarzma"),
    V("lentepi", "ლენტეფი", "Lentepi"),
    V("melse", "მელსე", "Melse"),
    V("monasteri", "მონასტერი", "Monasteri"),
    V("pokho", "პოხო", "Pokho"),
    V("saro", "სარო", "Saro"),
    V("ude", "უდე", "Ude"),
    V("persa", "ფერსა", "Persa"),
    V("shosheti", "შოშეთი", "Shosheti"),
    V("chorchana", "ჩორჩანა", "Chorchana"),
    V("tsakhi", "წახი", "Tsakhi"),
    V("tsqaltashua", "წყალთაშუა", "Tsqaltashua"),
    V("khevasheni", "ხევაშენი", "Khevasheni"),
    V("kharjami", "ხარჯამი", "Kharjami"),
  ],
  ambrolauri: [
    V("ablakha", "აბლახა", "Ablakha"),
    V("agara", "აგარა", "Agara"),
    V("ambrolauri", "ამბროლაური", "Ambrolauri"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("barakoni", "ბარაკონი", "Barakoni"),
    V("betlevi", "ბეთლევი", "Betlevi"),
    V("gora", "გორა", "Gora"),
    V("jvarismkhari", "ჯვარისმხარი", "Jvarismkhari"),
    V("zeda-tlughi", "ზედა თლუღი", "Zeda Tlughi"),
    V("zemo-krikhi", "ზემო კრიხი", "Zemo Krikhi"),
    V("znakva", "ზნაკვა", "Znakva"),
    V("ilta", "ილტა", "Ilta"),
    V("katsracheti", "კაცრაჭეთი", "Katsracheti"),
    V("krikhi", "კრიხი", "Krikhi"),
    V("litani", "ლიტანი", "Litani"),
    V("mordzgveti", "მორძგვეთი", "Mordzgveti"),
    V("nikortsminda", "ნიკორწმინდა", "Nikortsminda"),
    V("patara-opreti", "პატარა ოფრეთი", "Patara Opreti"),
    V("saqavre", "საყავრე", "Saqavre"),
    V("skhvava", "სხვავა", "Skhvava"),
    V("tlughi", "ტლუღი", "Tlughi"),
    V("putieti", "ფუტიეთი", "Putieti"),
    V("kveda-krikhi", "ქვედა კრიხი", "Kveda Krikhi"),
    V("shardometi", "შარდომეთი", "Shardometi"),
    V("chorchana", "ჩორჩანა", "Chorchana"),
    V("tsesi", "წესი", "Tsesi"),
    V("khvanchkara", "ხვანჭკარა", "Khvanchkara"),
    V("jvarisa", "ჯვარისა", "Jvarisa"),
  ],
  aspindza: [
    V("agara", "აგარა", "Agara"),
    V("aspindza", "ასპინძა", "Aspindza"),
    V("vargavi", "ვარგავი", "Vargavi"),
    V("zemo-vardzia", "ზემო ვარძია", "Zemo Vardzia"),
    V("ivlita", "ივლიტა", "Ivlita"),
    V("kartsakhi", "კარწახი", "Kartsakhi"),
    V("leliani", "ლელიანი", "Leliani"),
    V("nakalakevi", "ნაქალაქევი", "Nakalakevi"),
    V("orgora", "ორგორა", "Orgora"),
    V("rustavi", "რუსთავი", "Rustavi"),
    V("saqure", "საყურე", "Saqure"),
    V("toloshi", "ტოლოში", "Toloshi"),
    V("pia", "ფია", "Pia"),
    V("dzveli-vardzia", "ძველი ვარძია", "Dzveli Vardzia"),
    V("tsatsqali", "წაწყალი", "Tsatsqali"),
    V("khizabavra", "ხიზაბავრა", "Khizabavra"),
  ],
  akhalgori: [
    V("akhalgori", "ახალგორი", "Akhalgori"),
    V("balaantkari", "ბალაანთკარი", "Balaantkari"),
    V("gamarjveba", "გამარჯვება", "Gamarjveba"),
    V("gveleti", "გველეთი", "Gveleti"),
    V("darkveti", "დარკვეთი", "Darkveti"),
    V("vardisubani", "ვარდისუბანი", "Vardisubani"),
    V("zakhuri", "ზახური", "Zakhuri"),
    V("tevdormakhi", "თევდორმახი", "Tevdormakhi"),
    V("largvisi", "ლარგვისი", "Largvisi"),
    V("makhie", "მახიე", "Makhie"),
    V("mejvriskhevi", "მეჯვრისხევი", "Mejvriskhevi"),
    V("orchosani", "ორჭოსანი", "Orchosani"),
    V("kurtati", "ქურთათი", "Kurtati"),
    V("shubani", "შუბანი", "Shubani"),
    V("tsirkvali", "წირქვალი", "Tsirkvali"),
    V("kharbali", "ხარბალი", "Kharbali"),
  ],
  akhalkalaki: [
    V("abuli", "აბული", "Abuli"),
    V("alastani", "ალასტანი", "Alastani"),
    V("apnia", "აფნია", "Apnia"),
    V("bavra", "ბავრა", "Bavra"),
    V("burnasheti", "ბურნაშეთი", "Burnasheti"),
    V("gogasheni", "გოგაშენი", "Gogasheni"),
    V("dadeshi", "დადეში", "Dadeshi"),
    V("dilipi", "დილიფი", "Dilipi"),
    V("evtopeli", "ევტოფელი", "Evtopeli"),
    V("zako", "ზაკო", "Zako"),
    V("korkhi", "კორხი", "Korkhi"),
    V("kokhia", "კოხია", "Kokhia"),
    V("kumurdo", "კუმურდო", "Kumurdo"),
    V("lomaturtskhi", "ლომატურცხი", "Lomaturtskhi"),
    V("madatpa", "მადათფა", "Madatpa"),
    V("mikhailovka", "მიხაილოვკა", "Mikhailovka"),
    V("moduma", "მოდუმა", "Moduma"),
    V("murjakheti", "მურჯახეთი", "Murjakheti"),
    V("okhora", "ოხორა", "Okhora"),
    V("tba", "ტბა", "Tba"),
    V("kvemo-apnia", "ქვემო აფნია", "Kvemo Apnia"),
    V("kartse", "ქარცე", "Kartse"),
    V("khospio", "ხოსპიო", "Khospio"),
    V("chunchkha", "ჩუნჩხა", "Chunchkha"),
    V("kochio", "კოჭიო", "Kochio"),
  ],
  akhaltsikhe: [
    V("abastumani", "აბასთუმანი", "Abastumani"),
    V("andriatsminda", "ანდრიაწმინდა", "Andriatsminda"),
    V("akri", "აკრი", "Akri"),
    V("bqari", "ბყარი", "Bqari"),
    V("gurkeli", "გურკელი", "Gurkeli"),
    V("daba", "დაბა", "Daba"),
    V("didi-samsari", "დიდი სამსარი", "Didi Samsari"),
    V("didi-margeni", "დიდი მარგენი", "Didi Margeni"),
    V("iqalta", "იყალთა", "Iqalta"),
    V("klde", "კლდე", "Klde"),
    V("minadze", "მინაძე", "Minadze"),
    V("mokhe", "მოხე", "Mokhe"),
    V("mrevli", "მრევლი", "Mrevli"),
    V("patara-samsari", "პატარა სამსარი", "Patara Samsari"),
    V("sviri", "სვირი", "Sviri"),
    V("persa", "ფერსა", "Persa"),
    V("kvabliani", "ქვაბლიანი", "Kvabliani"),
    V("qulalisi", "ყულალისი", "Qulalisi"),
    V("tsikhisdziri", "ციხისძირი", "Tsikhisdziri"),
    V("dzruli", "ძრული", "Dzruli"),
    V("tsvintri", "წვინტრი", "Tsvintri"),
    V("khaki", "ხაკი", "Khaki"),
  ],
  akhmeta: [
    V("atsquri", "აწყური", "Atsquri"),
    V("akhmeta", "ახმეტა", "Akhmeta"),
    V("bachao", "ბაჩაო", "Bachao"),
    V("bakhtrioni", "ბახტრიონი", "Bakhtrioni"),
    V("gorana", "გორანა", "Gorana"),
    V("dedisperdi", "დედისფერდი", "Dedisperdi"),
    V("zemo-khodasheni", "ზემო ხოდაშენი", "Zemo Khodasheni"),
    V("torghva", "თორღვა", "Torghva"),
    V("kasristsqali", "კასრისწყალი", "Kasristsqali"),
    V("maghraani", "მაღრაანი", "Maghraani"),
    V("matani", "მატანი", "Matani"),
    V("ozhio", "ოჟიო", "Ozhio"),
    V("pankisis-kheoba", "პანკისის ხეობა", "Pankisis Kheoba"),
    V("saakadze", "სააკაძე", "Saakadze"),
    V("saatmiro", "საათმირო", "Saatmiro"),
    V("sakobiano", "საკობიანო", "Sakobiano"),
    V("samtatsqaro", "სამთაწყარო", "Samtatsqaro"),
    V("sakobo", "საქობო", "Sakobo"),
    V("kvemo-khodasheni", "ქვემო ხოდაშენი", "Kvemo Khodasheni"),
    V("shakhvetila", "შახვეტილა", "Shakhvetila"),
    V("choloqauri", "ჩოლოყაური", "Choloqauri"),
    V("tsitsamura", "წიწამურა", "Tsitsamura"),
    V("khorbalo", "ხორბალო", "Khorbalo"),
  ],
  baghdati: [
    V("alismereti", "ალისმერეთი", "Alismereti"),
    V("dapenili", "დაფენილი", "Dapenili"),
    V("didvela", "დიდველა", "Didvela"),
    V("dimi", "დიმი", "Dimi"),
    V("vartsikhe", "ვარციხე", "Vartsikhe"),
    V("zegani", "ზეგანი", "Zegani"),
    V("kakaskhidi", "კაკასხიდი", "Kakaskhidi"),
    V("korishi", "კორიში", "Korishi"),
    V("mamaneti", "მამანეთი", "Mamaneti"),
    V("meore-obcha", "მეორე ობჩა", "Meore Obcha"),
    V("nergeeti", "ნერგეეთი", "Nergeeti"),
    V("pirveli-obcha", "პირველი ობჩა", "Pirveli Obcha"),
    V("rokiti", "როკითი", "Rokiti"),
    V("rokhi", "როხი", "Rokhi"),
    V("saimedo", "საიმედო", "Saimedo"),
    V("sakraula", "საკრაულა", "Sakraula"),
    V("persati", "ფერსათი", "Persati"),
    V("kershaveti", "ქერშავეთი", "Kershaveti"),
    V("shubani", "შუბანი", "Shubani"),
    V("tsablaraskhevi", "წაბლარასხევი", "Tsablaraskhevi"),
    V("tsitelkhevi", "წითელხევი", "Tsitelkhevi"),
    V("tsqaltashua", "წყალთაშუა", "Tsqaltashua"),
    V("khani", "ხანი", "Khani"),
  ],
  bolnisi: [
    V("akaurta", "აკაურთა", "Akaurta"),
    V("arkiposa", "არქიფოსა", "Arkiposa"),
    V("balichi", "ბალიჭი", "Balichi"),
    V("bolnisi", "ბოლნისი", "Bolnisi"),
    V("botarebi", "ბოტარები", "Botarebi"),
    V("darbazi", "დარბაზი", "Darbazi"),
    V("disevi", "დისევი", "Disevi"),
    V("zvare", "ზვარე", "Zvare"),
    V("tamarisi", "თამარისი", "Tamarisi"),
    V("kazreti", "კაზრეთი", "Kazreti"),
    V("mamkhuti", "მამხუტი", "Mamkhuti"),
    V("mzhavamtsqali", "მჟავამწყალი", "Mzhavamtsqali"),
    V("nakhiduri", "ნახიდური", "Nakhiduri"),
    V("patara-dmanisi", "პატარა დმანისი", "Patara Dmanisi"),
    V("ratevani", "რატევანი", "Ratevani"),
    V("sadakhlo", "სადახლო", "Sadakhlo"),
    V("samshvilde", "სამშვილდე", "Samshvilde"),
    V("poladauri", "ფოლადაური", "Poladauri"),
    V("kvemo-bolnisi", "ქვემო ბოლნისი", "Kvemo Bolnisi"),
    V("dzveli-bolnisi", "ძველი ბოლნისი", "Dzveli Bolnisi"),
    V("khaishi", "ხაიში", "Khaishi"),
    V("khatissopeli", "ხატისსოფელი", "Khatissopeli"),
  ],
  borjomi: [
    V("akhaldaba", "ახალდაბა", "Akhaldaba"),
    V("bakuriani", "ბაკურიანი", "Bakuriani"),
    V("bakurianis-andeziti", "ბაკურიანის ანდეზიტი", "Bakurianis Andeziti"),
    V("borjomi", "ბორჯომი", "Borjomi"),
    V("gverdisubani", "გვერდისუბანი", "Gverdisubani"),
    V("gujareti", "გუჯარეთი", "Gujareti"),
    V("daba", "დაბა", "Daba"),
    V("dviri", "დვირი", "Dviri"),
    V("vardzia", "ვარძია", "Vardzia"),
    V("tmogvi", "თმოგვი", "Tmogvi"),
    V("mzetamze", "მზეთამზე", "Mzetamze"),
    V("patara-mitarbi", "პატარა მიტარბი", "Patara Mitarbi"),
    V("rvelisi", "რველისი", "Rvelisi"),
    V("saqure", "საყურე", "Saqure"),
    V("sadgeri", "სადგერი", "Sadgeri"),
    V("tashiskari", "ტაშისკარი", "Tashiskari"),
    V("qvibisi", "ყვიბისი", "Qvibisi"),
    V("tsaghveri", "წაღვერი", "Tsaghveri"),
    V("chikharula", "ჭიხარულა", "Chikharula"),
  ],
  gardabani: [
    V("agtakia", "აგთაკია", "Agtakia"),
    V("araplo", "არაფლო", "Araplo"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("botarebi", "ბოტარები", "Botarebi"),
    V("gardabani", "გარდაბანი", "Gardabani"),
    V("gachiani", "გაჩიანი", "Gachiani"),
    V("darbazi", "დარბაზი", "Darbazi"),
    V("vakhtangisi", "ვახტანგისი", "Vakhtangisi"),
    V("krtsanisi", "კრწანისი", "Krtsanisi"),
    V("lemshveniera", "ლემშვენიერა", "Lemshveniera"),
    V("martqopi", "მარტყოფი", "Martqopi"),
    V("mughanlo", "მუღანლო", "Mughanlo"),
    V("nazarlo", "ნაზარლო", "Nazarlo"),
    V("norio", "ნორიო", "Norio"),
    V("patara-lelovani", "პატარა ლელოვანი", "Patara Lelovani"),
    V("saartichala", "საართიჭალა", "Saartichala"),
    V("tarasovka", "ტარასოვკა", "Tarasovka"),
    V("pona", "ფონა", "Pona"),
    V("kvemo-taleti", "ქვემო თალეთი", "Kvemo Taleti"),
    V("qarajalari", "ყარაჯალარი", "Qarajalari"),
    V("jandari", "ჯანდარი", "Jandari"),
  ],
  gurjaani: [
    V("arashenda", "არაშენდა", "Arashenda"),
    V("akhasheni", "ახაშენი", "Akhasheni"),
    V("akaurtebi", "აკაურთები", "Akaurtebi"),
    V("vejini", "ვეჯინი", "Vejini"),
    V("zemo-kachreti", "ზემო კაჭრეთი", "Zemo Kachreti"),
    V("ziari", "ზიარი", "Ziari"),
    V("tamariani", "თამარიანი", "Tamariani"),
    V("kardenakhi", "კარდენახი", "Kardenakhi"),
    V("kachreti", "კაჭრეთი", "Kachreti"),
    V("kolagi", "კოლაგი", "Kolagi"),
    V("melaani", "მელაანი", "Melaani"),
    V("kuchatani", "კუჭატანი", "Kuchatani"),
    V("mukuzani", "მუკუზანი", "Mukuzani"),
    V("naniani", "ნანიანი", "Naniani"),
    V("patardzeuli", "პატარძეული", "Patardzeuli"),
    V("sanage", "სანაგე", "Sanage"),
    V("somkhiti", "სომხითი", "Somkhiti"),
    V("pkhoveli", "ფხოველი", "Pkhoveli"),
    V("kvemo-kachreti", "ქვემო კაჭრეთი", "Kvemo Kachreti"),
    V("qitaani", "ყიტაანი", "Qitaani"),
    V("shashiani", "შაშიანი", "Shashiani"),
    V("chumlaqi", "ჩუმლაყი", "Chumlaqi"),
    V("dzirkvoki", "ძირკვოკი", "Dzirkvoki"),
    V("tsnori", "წნორი", "Tsnori"),
    V("chabukiani", "ჭაბუკიანი", "Chabukiani"),
    V("chandari", "ჭანდარი", "Chandari"),
  ],
  dedoplistskaro: [
    V("arkhiloskalo", "არხილოსკალო", "Arkhiloskalo"),
    V("gamarjveba", "გამარჯვება", "Gamarjveba"),
    V("davitiani", "დავითიანი", "Davitiani"),
    V("zemo-kedi", "ზემო ქედი", "Zemo Kedi"),
    V("irmasheni", "ირმაშენი", "Irmasheni"),
    V("sabatlo", "საბათლო", "Sabatlo"),
    V("samtatsqaro", "სამთაწყარო", "Samtatsqaro"),
    V("kvemo-kedi", "ქვემო ქედი", "Kvemo Kedi"),
    V("koshi", "ქოში", "Koshi"),
    V("ozaani", "ოზაანი", "Ozaani"),
    V("sarosi", "საროსი", "Sarosi"),
    V("pirosmani", "ფიროსმანი", "Pirosmani"),
    V("khornabuji", "ხორნაბუჯი", "Khornabuji"),
  ],
  dmanisi: [
    V("amamlo", "ამამლო", "Amamlo"),
    V("bostani", "ბოსტანი", "Bostani"),
    V("gamarjveba", "გამარჯვება", "Gamarjveba"),
    V("gantiadi", "განთიადი", "Gantiadi"),
    V("gora", "გორა", "Gora"),
    V("gordi", "გორდი", "Gordi"),
    V("dmanisi", "დმანისი", "Dmanisi"),
    V("didi-dmanisi", "დიდი დმანისი", "Didi Dmanisi"),
    V("vake", "ვაკე", "Vake"),
    V("izbasha", "იზბაშა", "Izbasha"),
    V("kamarlo", "კამარლო", "Kamarlo"),
    V("karabulakhi", "კარაბულახი", "Karabulakhi"),
    V("kirbali", "კირბალი", "Kirbali"),
    V("mashavera", "მაშავერა", "Mashavera"),
    V("okropilo", "ოქროპილო", "Okropilo"),
    V("patara-dmanisi", "პატარა დმანისი", "Patara Dmanisi"),
    V("sarvani", "სარვანი", "Sarvani"),
    V("sakire", "საკირე", "Sakire"),
    V("tonteti", "ტონთეთი", "Tonteti"),
    V("pinezauri", "ფინეზაური", "Pinezauri"),
    V("kosalari", "ქოსალარი", "Kosalari"),
    V("shakhmirlo", "შახმირლო", "Shakhmirlo"),
    V("chocheti", "ჩოჩეთი", "Chocheti"),
    V("tsepa", "წეფა", "Tsepa"),
    V("chochiani", "ჭოჭიანი", "Chochiani"),
  ],
  dusheti: [
    V("aragvispiri", "არაგვისპირი", "Aragvispiri"),
    V("bazaleti", "ბაზალეთი", "Bazaleti"),
    V("beglarbegkhevi", "ბეგლარბეგხევი", "Beglarbegkhevi"),
    V("bistro", "ბისტრო", "Bistro"),
    V("bursachiri", "ბურსაჭირი", "Bursachiri"),
    V("gveleti", "გველეთი", "Gveleti"),
    V("dusheti", "დუშეთი", "Dusheti"),
    V("zindzikhi", "ზინძიხი", "Zindzikhi"),
    V("kanatia", "კანატია", "Kanatia"),
    V("lapanaantkari", "ლაფანაანთკარი", "Lapanaantkari"),
    V("magharoskari", "მაღაროსკარი", "Magharoskari"),
    V("mchadijvari", "მჭადიჯვარი", "Mchadijvari"),
    V("nedzikhi", "ნეძიხი", "Nedzikhi"),
    V("patara-minda", "პატარა მინდა", "Patara Minda"),
    V("zhinvali", "ჟინვალი", "Zhinvali"),
    V("saguramo", "საგურამო", "Saguramo"),
    V("kvesheti", "ქვეშეთი", "Kvesheti"),
    V("shuapkho", "შუაფხო", "Shuapkho"),
    V("chirdili", "ჩირდილი", "Chirdili"),
    V("tsitelsopeli", "წითელსოფელი", "Tsitelsopeli"),
    V("choporti", "ჭოპორტი", "Choporti"),
  ],
  vani: [
    V("amaghleba", "ამაღლება", "Amaghleba"),
    V("bzvani", "ბზვანი", "Bzvani"),
    V("gormaghali", "გორმაღალი", "Gormaghali"),
    V("didmaghali", "დიდმაღალი", "Didmaghali"),
    V("dimi", "დიმი", "Dimi"),
    V("zemo-vani", "ზემო ვანი", "Zemo Vani"),
    V("itkhvisi", "ითხვისი", "Itkhvisi"),
    V("kvata", "კვათა", "Kvata"),
    V("mukhaqula", "მუხაყულა", "Mukhaqula"),
    V("obcha", "ობჩა", "Obcha"),
    V("salkhino", "სალხინო", "Salkhino"),
    V("sulori", "სულორი", "Sulori"),
    V("tibaani", "ტიბაანი", "Tibaani"),
    V("pereta", "ფერეთა", "Pereta"),
    V("kedmaghali", "ქედმაღალი", "Kedmaghali"),
    V("shuamta", "შუამთა", "Shuamta"),
    V("dzulukhi", "ძულუხი", "Dzulukhi"),
    V("tsulukidze", "წულუკიძე", "Tsulukidze"),
    V("khunevi", "ხუნევი", "Khunevi"),
  ],
  zestaponi: [
    V("alaverdi", "ალავერდი", "Alaverdi"),
    V("argveta", "არგვეთა", "Argveta"),
    V("boslevi", "ბოსლევი", "Boslevi"),
    V("bzvani", "ბზვანი", "Bzvani"),
    V("didi-gomareti", "დიდი გომარეთი", "Didi Gomareti"),
    V("didi-dagnari", "დიდი დაგნარი", "Didi Dagnari"),
    V("dilikauri", "დილიკაური", "Dilikauri"),
    V("zovreti", "ზოვრეთი", "Zovreti"),
    V("tavasa", "თავასა", "Tavasa"),
    V("korojani", "კოროჯანი", "Korojani"),
    V("zeda-sazano", "ზედა საზანო", "Zeda Sazano"),
    V("kveda-sazano", "ქვედა საზანო", "Kveda Sazano"),
    V("pirveli-sviri", "პირველი სვირი", "Pirveli Sviri"),
    V("meore-sviri", "მეორე სვირი", "Meore Sviri"),
    V("martotubani", "მარტოთუბანი", "Martotubani"),
    V("motipo", "მოთიფო", "Motipo"),
    V("obcha", "ობჩა", "Obcha"),
    V("pirveli-dzirula", "პირველი ძირულა", "Pirveli Dzirula"),
    V("rodinauli", "როდინაული", "Rodinauli"),
    V("sakasria", "საქასრია", "Sakasria"),
    V("sanakhshire", "სანახშირე", "Sanakhshire"),
    V("simoneti", "სიმონეთი", "Simoneti"),
    V("shorapani", "შორაპანი", "Shorapani"),
    V("chkhari", "ჩხარი", "Chkhari"),
    V("tseva", "წევა", "Tseva"),
    V("tseseti", "წესეთი", "Tseseti"),
    V("tskhratsqaro", "ცხრაწყარო", "Tskhratsqaro"),
    V("khreiti", "ხრეითი", "Khreiti"),
  ],
  tetritskaro: [
    V("ardisheni", "არდიშენი", "Ardisheni"),
    V("asureti", "ასურეთი", "Asureti"),
    V("borbalo", "ბორბალო", "Borbalo"),
    V("vashlovani", "ვაშლოვანი", "Vashlovani"),
    V("tetritsqaro", "თეთრიწყარო", "Tetritsqaro"),
    V("iraga", "ირაგა", "Iraga"),
    V("kodistsqaro", "კოდისწყარო", "Kodistsqaro"),
    V("marabda", "მარაბდა", "Marabda"),
    V("manglisi", "მანგლისი", "Manglisi"),
    V("mukhati", "მუხათი", "Mukhati"),
    V("orbeti", "ორბეთი", "Orbeti"),
    V("patara-dmanisi", "პატარა დმანისი", "Patara Dmanisi"),
    V("saghrasheni", "საღრაშენი", "Saghrasheni"),
    V("tabatsquri", "ტაბაწყური", "Tabatsquri"),
    V("partskhisi", "ფარცხისი", "Partskhisi"),
    V("kvemo-aguara", "ქვემო აგუარა", "Kvemo Aguara"),
    V("dzveli-marabda", "ძველი მარაბდა", "Dzveli Marabda"),
    V("tsqluleti", "წყლულეთი", "Tsqluleti"),
    V("khuluti", "ხულუტი", "Khuluti"),
  ],
  telavi: [
    V("akura", "აკურა", "Akura"),
    V("artana", "ართანა", "Artana"),
    V("busheti", "ბუშეთი", "Busheti"),
    V("gulgula", "გულგულა", "Gulgula"),
    V("iqalto", "იყალთო", "Iqalto"),
    V("kurdghelauri", "კურდღელაური", "Kurdghelauri"),
    V("lalisquri", "ლალისყური", "Lalisquri"),
    V("napareuli", "ნაფარეული", "Napareuli"),
    V("patara-khevsuri", "პატარა ხევსური", "Patara Khevsuri"),
    V("ruispiri", "რუისპირი", "Ruispiri"),
    V("saniore", "სანიორე", "Saniore"),
    V("pshaveli", "ფშაველი", "Pshaveli"),
    V("kistauri", "ქისტაური", "Kistauri"),
    V("qarajala", "ყარაჯალა", "Qarajala"),
    V("shalauri", "შალაური", "Shalauri"),
    V("chumlaqi", "ჩუმლაყი", "Chumlaqi"),
    V("tsinandali", "წინანდალი", "Tsinandali"),
    V("jughaani", "ჯუღაანი", "Jughaani"),
  ],
  terjola: [
    V("alaverdi", "ალავერდი", "Alaverdi"),
    V("argeneti", "არგენეთი", "Argeneti"),
    V("godogani", "გოდოგანი", "Godogani"),
    V("didi-rupoti", "დიდი რუფოთი", "Didi Rupoti"),
    V("zemo-simoneti", "ზემო სიმონეთი", "Zemo Simoneti"),
    V("terjola", "თერჯოლა", "Terjola"),
    V("kvakhvreli", "კვახვრელი", "Kvakhvreli"),
    V("nakhshirghele", "ნახშირღელე", "Nakhshirghele"),
    V("ozaani", "ოზაანი", "Ozaani"),
    V("patara-rupoti", "პატარა რუფოთი", "Patara Rupoti"),
    V("sakraula", "საკრაულა", "Sakraula"),
    V("siktura", "სიქთურა", "Siktura"),
    V("kveda-simoneti", "ქვედა სიმონეთი", "Kveda Simoneti"),
    V("chkhari", "ჩხარი", "Chkhari"),
    V("chikha", "ჩიხა", "Chikha"),
    V("dzevri", "ძევრი", "Dzevri"),
    V("tsiaghubani", "წიაღუბანი", "Tsiaghubani"),
    V("zhoneti", "ჟონეთი", "Zhoneti"),
  ],
  tianeti: [
    V("boko", "ბოკო", "Boko"),
    V("gamoghma-aragvi", "გამოღმა არაგვი", "Gamoghma Aragvi"),
    V("zaridzeebi", "ზარიძეები", "Zaridzeebi"),
    V("tianeti", "თიანეთი", "Tianeti"),
    V("truso", "თრუსო", "Truso"),
    V("katsalkhevi", "კაწალხევი", "Katsalkhevi"),
    V("lelubani", "ლელუბანი", "Lelubani"),
    V("naduknebi", "ნადუქნები", "Naduknebi"),
    V("zhebota", "ჟებოტა", "Zhebota"),
    V("saqdrioni", "საყდრიონი", "Saqdrioni"),
    V("tolaantkari", "ტოლაანთკარი", "Tolaantkari"),
    V("kvemo-artani", "ქვემო არტანი", "Kvemo Artani"),
    V("sharakhevi", "შარახევი", "Sharakhevi"),
    V("chiortoli", "ჩიორთოლი", "Chiortoli"),
    V("tsintsqali", "წინწყალი", "Tsintsqali"),
    V("khevsurtsopeli", "ხევსურთსოფელი", "Khevsurtsopeli"),
  ],
  kaspi: [
    V("agara", "აგარა", "Agara"),
    V("akhalkalaki", "ახალქალაქი", "Akhalkalaki"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("barnabiani", "ბარნაბიანი", "Barnabiani"),
    V("boshuri", "ბოშური", "Boshuri"),
    V("gavazi", "გავაზი", "Gavazi"),
    V("gariqula", "გარიყულა", "Gariqula"),
    V("gombori", "გომბორი", "Gombori"),
    V("grakali", "გრაკალი", "Grakali"),
    V("doesi", "დოესი", "Doesi"),
    V("ertmitsa", "ერთმიწა", "Ertmitsa"),
    V("zemo-khandaki", "ზემო ხანდაკი", "Zemo Khandaki"),
    V("tedzami", "თეძამი", "Tedzami"),
    V("kavtiskhevi", "კავთისხევი", "Kavtiskhevi"),
    V("kodistsqaro", "კოდისწყარო", "Kodistsqaro"),
    V("lavriskhevi", "ლავრისხევი", "Lavriskhevi"),
    V("mejvriskhevi", "მეჯვრისხევი", "Mejvriskhevi"),
    V("monasteri", "მონასტერი", "Monasteri"),
    V("noste", "ნოსტე", "Noste"),
    V("orkhevi", "ორხევი", "Orkhevi"),
    V("patara-gorijvari", "პატარა გორიჯვარი", "Patara Gorijvari"),
    V("rkoni", "რკონი", "Rkoni"),
    V("samtavisi", "სამთავისი", "Samtavisi"),
    V("sasireti", "სასირეთი", "Sasireti"),
    V("sadabi", "სადაბი", "Sadabi"),
    V("tqviavi", "ტყვიავი", "Tqviavi"),
    V("kvemo-khandaki", "ქვემო ხანდაკი", "Kvemo Khandaki"),
    V("ktsiisqure", "ქციისყურე", "Ktsiisqure"),
    V("ghogheti", "ღოღეთი", "Ghogheti"),
    V("shindisi", "შინდისი", "Shindisi"),
    V("chachubeti", "ჩაჩუბეთი", "Chachubeti"),
    V("dzevera", "ძევერა", "Dzevera"),
    V("tseesi", "წეესი", "Tseesi"),
    V("tsilkani", "წილკანი", "Tsilkani"),
    V("chandari", "ჭანდარი", "Chandari"),
    V("khovle", "ხოვლე", "Khovle"),
  ],
  lagodekhi: [
    V("apeni", "აფენი", "Apeni"),
    V("baisubani", "ბაისუბანი", "Baisubani"),
    V("vardisubani", "ვარდისუბანი", "Vardisubani"),
    V("gantiadi", "განთიადი", "Gantiadi"),
    V("gurgeniani", "გურგენიანი", "Gurgeniani"),
    V("zemo-naniani", "ზემო ნანიანი", "Zemo Naniani"),
    V("kabali", "კაბალი", "Kabali"),
    V("lelovani", "ლელოვანი", "Lelovani"),
    V("mele", "მელე", "Mele"),
    V("ninigori", "ნინიგორი", "Ninigori"),
    V("patara-gorijvari", "პატარა გორიჯვარი", "Patara Gorijvari"),
    V("rachisubani", "რაჭისუბანი", "Rachisubani"),
    V("sakobo", "საქობო", "Sakobo"),
    V("kvemo-naniani", "ქვემო ნანიანი", "Kvemo Naniani"),
    V("qachaghiani", "ყაჩაღიანი", "Qachaghiani"),
    V("shroma", "შრომა", "Shroma"),
    V("chabukiani", "ჭაბუკიანი", "Chabukiani"),
    V("chontio", "ჭონთიო", "Chontio"),
  ],
  lanchkhuti: [
    V("aketi", "აკეთი", "Aketi"),
    V("askana", "ასკანა", "Askana"),
    V("atsana", "აცანა", "Atsana"),
    V("baghmakho", "ბაღმახო", "Baghmakho"),
    V("gvimraichala", "გვიმრაიჭალა", "Gvimraichala"),
    V("guliani", "გულიანი", "Guliani"),
    V("lanchkhuti", "ლანჩხუთი", "Lanchkhuti"),
    V("leliani", "ლელიანი", "Leliani"),
    V("lesa", "ლესა", "Lesa"),
    V("machkhvareti", "მაჩხვარეთი", "Machkhvareti"),
    V("mamati", "მამათი", "Mamati"),
    V("mshvidobauri", "მშვიდობაური", "Mshvidobauri"),
    V("nigvziani", "ნიგვზიანი", "Nigvziani"),
    V("patara-supsa", "პატარა სუფსა", "Patara Supsa"),
    V("satsikhuri", "საციხური", "Satsikhuri"),
    V("supsa", "სუფსა", "Supsa"),
    V("chibati", "ჩიბათი", "Chibati"),
    V("chochkhati", "ჩოჩხათი", "Chochkhati"),
    V("dzimiti", "ძიმითი", "Dzimiti"),
    V("tsqaltsminda", "წყალწმინდა", "Tsqaltsminda"),
  ],
  lentekhi: [
    V("askhi", "ასხი", "Askhi"),
    V("babilo", "ბაბილო", "Babilo"),
    V("gopura", "გოფურა", "Gopura"),
    V("lentekhi", "ლენტეხი", "Lentekhi"),
    V("lechkhubi", "ლეჩხუბი", "Lechkhubi"),
    V("machkhaari", "მაჩხაარი", "Machkhaari"),
    V("mzhava", "მჟავა", "Mzhava"),
    V("rtskhmeluri", "რცხმელური", "Rtskhmeluri"),
    V("saqdriari", "საყდრიარი", "Saqdriari"),
    V("tvibi", "ტვიბი", "Tvibi"),
    V("chikhareshi", "ჩიხარეში", "Chikhareshi"),
    V("khopuri", "ხოფური", "Khopuri"),
    V("khesheli", "ხეშელი", "Khesheli"),
  ],
  marneuli: [
    V("abazulo", "აბაზულო", "Abazulo"),
    V("algeti", "ალგეთი", "Algeti"),
    V("araplo", "არაფლო", "Araplo"),
    V("akhalkalaki", "ახალქალაქი", "Akhalkalaki"),
    V("baidari", "ბაიდარი", "Baidari"),
    V("beglari", "ბეგლარი", "Beglari"),
    V("beitarami", "ბეითარამი", "Beitarami"),
    V("burma", "ბურმა", "Burma"),
    V("gulbaghi", "გულბაღი", "Gulbaghi"),
    V("dashtapa", "დაშთაფა", "Dashtapa"),
    V("didamzha", "დიდამჟა", "Didamzha"),
    V("imiri", "იმირი", "Imiri"),
    V("kasumlo", "კასუმლო", "Kasumlo"),
    V("kesalo", "ქესალო", "Kesalo"),
    V("kutliari", "ქუთლიარი", "Kutliari"),
    V("mardani", "მარდანი", "Mardani"),
    V("mtevana", "მტევანა", "Mtevana"),
    V("norgiughi", "ნორგიუღი", "Norgiughi"),
    V("opereti", "ოპერეთი", "Opereti"),
    V("sadakhlo", "სადახლო", "Sadakhlo"),
    V("sulda", "სულდა", "Sulda"),
    V("tamazlu", "ტამაზლუ", "Tamazlu"),
    V("qizilajlo", "ყიზილაჯლო", "Qizilajlo"),
    V("shaumiani", "შაუმიანი", "Shaumiani"),
    V("chanakhchi", "ჩანახჩი", "Chanakhchi"),
    V("tsereteli", "წერეთელი", "Tsereteli"),
  ],
  martvili: [
    V("abedati", "აბედათი", "Abedati"),
    V("almati", "ალმათი", "Almati"),
    V("bandza", "ბანძა", "Bandza"),
    V("gachedili", "გაჭედილი", "Gachedili"),
    V("didi-chqoni", "დიდი ჭყონი", "Didi Chqoni"),
    V("didi-chkhorotsqu", "დიდი ჩხოროწყუ", "Didi Chkhorotsqu"),
    V("vedidkari", "ვედიდკარი", "Vedidkari"),
    V("zana", "ზანა", "Zana"),
    V("kurzu", "კურზუ", "Kurzu"),
    V("lekhaindrao", "ლეხაინდრაო", "Lekhaindrao"),
    V("mukhurcha", "მუხურჩა", "Mukhurcha"),
    V("nagvazao", "ნაგვაზაო", "Nagvazao"),
    V("salkhino", "სალხინო", "Salkhino"),
    V("sega", "სეგა", "Sega"),
    V("tqachiri", "ტყაჩირი", "Tqachiri"),
    V("kalkva", "ქალქვა", "Kalkva"),
    V("kveda-nogha", "ქვედა ნოღა", "Kveda Nogha"),
    V("chochkhati", "ჩოჩხათი", "Chochkhati"),
    V("chaladidi", "ჭალადიდი", "Chaladidi"),
    V("khidi", "ხიდი", "Khidi"),
  ],
  mestia: [
    V("adishi", "ადიში", "Adishi"),
    V("ala", "ალა", "Ala"),
    V("becho", "ბეჩო", "Becho"),
    V("guli", "გული", "Guli"),
    V("dolasveri", "დოლასვერი", "Dolasveri"),
    V("eteri", "ეთერი", "Eteri"),
    V("zardlashi", "ზარდლაში", "Zardlashi"),
    V("ipari", "იფარი", "Ipari"),
    V("lakhmudi", "ლახმუდი", "Lakhmudi"),
    V("lentekhi", "ლენტეხი", "Lentekhi"),
    V("latali", "ლატალი", "Latali"),
    V("mestia", "მესტია", "Mestia"),
    V("muzhashi", "მუჟაში", "Muzhashi"),
    V("mukhasheni", "მუხაშენი", "Mukhasheni"),
    V("nakra", "ნაკრა", "Nakra"),
    V("svimoni", "სვიმონი", "Svimoni"),
    V("ushguli", "უშგული", "Ushguli"),
    V("paris", "ფარის", "Paris"),
    V("chubinlari", "ჩუბინლარი", "Chubinlari"),
    V("khaishi", "ხაიში", "Khaishi"),
    V("tsalda", "ცალდა", "Tsalda"),
  ],
  mtskheta: [
    V("avchala", "ავჭალა", "Avchala"),
    V("akhaldaba", "ახალდაბა", "Akhaldaba"),
    V("armazi", "არმაზი", "Armazi"),
    V("bevreti", "ბევრეთი", "Bevreti"),
    V("dzegvi", "ძეგვი", "Dzegvi"),
    V("vardisubani", "ვარდისუბანი", "Vardisubani"),
    V("zakaria", "ზაქარია", "Zakaria"),
    V("karsani", "კარსანი", "Karsani"),
    V("kotoraantkari", "კოტორაანთკარი", "Kotoraantkari"),
    V("mtskheta", "მცხეთა", "Mtskheta"),
    V("mukhrani", "მუხრანი", "Mukhrani"),
    V("navdaraantkari", "ნავდარაანთკარი", "Navdaraantkari"),
    V("nichbisi", "ნიჩბისი", "Nichbisi"),
    V("patara-kandai", "პატარა კანდაი", "Patara Kandai"),
    V("saguramo", "საგურამო", "Saguramo"),
    V("satovle", "სათოვლე", "Satovle"),
    V("tabatsquri", "ტაბაწყური", "Tabatsquri"),
    V("kvemo-nichbisi", "ქვემო ნიჩბისი", "Kvemo Nichbisi"),
    V("ksovrisi", "ქსოვრისი", "Ksovrisi"),
    V("dzalisi", "ძალისი", "Dzalisi"),
    V("tsinamdzghvriantkari", "წინამძღვრიანთკარი", "Tsinamdzghvriantkari"),
    V("tserovani", "წეროვანი", "Tserovani"),
    V("tsqluleti", "წყლულეთი", "Tsqluleti"),
    V("chilovani", "ჭილოვანი", "Chilovani"),
    V("khekordzi", "ხეკორძი", "Khekordzi"),
    V("jighaura", "ჯიღაურა", "Jighaura"),
  ],
  ninotsminda: [
    V("gandza", "განძა", "Gandza"),
    V("gorelovka", "გორელოვკა", "Gorelovka"),
    V("didi-aragali", "დიდი არაგალი", "Didi Aragali"),
    V("epremovka", "ეფრემოვკა", "Epremovka"),
    V("tortia", "თორტია", "Tortia"),
    V("katnao", "კატნაო", "Katnao"),
    V("majdia", "მაჯდია", "Majdia"),
    V("ninotsminda", "ნინოწმინდა", "Ninotsminda"),
    V("orojalari", "ოროჯალარი", "Orojalari"),
    V("patara-aragali", "პატარა არაგალი", "Patara Aragali"),
    V("rodniki", "როდნიკი", "Rodniki"),
    V("satkhe", "სათხე", "Satkhe"),
    V("spasovka", "სპასოვკა", "Spasovka"),
    V("poka", "ფოკა", "Poka"),
    V("qaurma", "ყაურმა", "Qaurma"),
    V("chkhirashi", "ჩხირაში", "Chkhirashi"),
    V("jigrasheni", "ჯიგრაშენი", "Jigrasheni"),
  ],
  ozurgeti: [
    V("anaseuli", "ანასეული", "Anaseuli"),
    V("askana", "ასკანა", "Askana"),
    V("aghmashenebeli", "აღმაშენებელი", "Aghmashenebeli"),
    V("bakhvi", "ბახვი", "Bakhvi"),
    V("bochvauri", "ბოჩვაური", "Bochvauri"),
    V("gaghma-dvab-i", "გაღმა დვაბዙი", "Gaghma Dvabዙi"),
    V("gurianta", "გურიანთა", "Gurianta"),
    V("daiseti", "დაისეთი", "Daiseti"),
    V("didvani", "დიდვანი", "Didvani"),
    V("dvab-i", "დვაბዙი", "Dvabዙi"),
    V("vakijvari", "ვაკიჯვარი", "Vakijvari"),
    V("zemo-bakhvi", "ზემო ბახვი", "Zemo Bakhvi"),
    V("tkhinvali", "თხინვალი", "Tkhinvali"),
    V("kviriketi", "კვირიკეთი", "Kviriketi"),
    V("laituri", "ლაითური", "Laituri"),
    V("likhauri", "ლიხაური", "Likhauri"),
    V("makvaneti", "მაკვანეთი", "Makvaneti"),
    V("meria", "მერია", "Meria"),
    V("mziani", "მზიანი", "Mziani"),
    V("mshvidobauri", "მშვიდობაური", "Mshvidobauri"),
    V("nasakirali", "ნასაკირალი", "Nasakirali"),
    V("natanebi", "ნატანები", "Natanebi"),
    V("neta", "ნეთა", "Neta"),
    V("ozurgeti", "ოზურგეთი", "Ozurgeti"),
    V("ormeti", "ორმეთი", "Ormeti"),
    V("zhvanieti", "ჟვანიეთი", "Zhvanieti"),
    V("sajavakho", "საჯავახო", "Sajavakho"),
    V("silauri", "სილაური", "Silauri"),
    V("skhvirtavi", "სხვირთავი", "Skhvirtavi"),
    V("ukanava", "უკანავა", "Ukanava"),
    V("shroma", "შრომა", "Shroma"),
    V("shemokmedi", "შემოქმედი", "Shemokmedi"),
    V("tskhemliskhidi", "ცხემლისხიდი", "Tskhemliskhidi"),
    V("tsitelmta", "წითელმთა", "Tsitelmta"),
    V("dzimiti", "ძიმითი", "Dzimiti"),
    V("chanieti", "ჭანიეთი", "Chanieti"),
    V("khvarbeti", "ხვარბეთი", "Khvarbeti"),
  ],
  sachkhere: [
    V("argveti", "არგვეთი", "Argveti"),
    V("bareuli", "ბარეული", "Bareuli"),
    V("bakhio", "ბახიო", "Bakhio"),
    V("gadami", "გადამი", "Gadami"),
    V("gorisa", "გორისა", "Gorisa"),
    V("dageti", "დაგეთი", "Dageti"),
    V("dorevani", "დორევანი", "Dorevani"),
    V("zemo-prone", "ზემო პრონე", "Zemo Prone"),
    V("itkhvisi", "ითხვისი", "Itkhvisi"),
    V("korbouli", "კორბოული", "Korbouli"),
    V("lechkhubi", "ლეჩხუბი", "Lechkhubi"),
    V("margveti", "მარგვეთი", "Margveti"),
    V("mordzgveti", "მორძგვეთი", "Mordzgveti"),
    V("perevi", "პერევი", "Perevi"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("savane", "სავანე", "Savane"),
    V("skhvitori", "სხვიტორი", "Skhvitori"),
    V("chalovani", "ჭალოვანი", "Chalovani"),
    V("chorvila", "ჭორვილა", "Chorvila"),
    V("shalaura", "შალაურა", "Shalaura"),
  ],
  sagarejo: [
    V("antoki", "ანთოკი", "Antoki"),
    V("arkhiloskalo", "არხილოსკალო", "Arkhiloskalo"),
    V("asureti", "ასურეთი", "Asureti"),
    V("badiauri", "ბადიაური", "Badiauri"),
    V("gareja", "გარეჯა", "Gareja"),
    V("gombori", "გომბორი", "Gombori"),
    V("didamzha", "დიდამჟა", "Didamzha"),
    V("dudzauri", "დუძაური", "Dudzauri"),
    V("vardisubani", "ვარდისუბანი", "Vardisubani"),
    V("iormughanlo", "იორმუღანლო", "Iormughanlo"),
    V("kakabeti", "კაკაბეთი", "Kakabeti"),
    V("mzisguli", "მზისგული", "Mzisguli"),
    V("manavi", "მანავი", "Manavi"),
    V("modzvri", "მოძვრი", "Modzvri"),
    V("patara-armazi", "პატარა არმაზი", "Patara Armazi"),
    V("saurmago", "საურმაგო", "Saurmago"),
    V("ujarma", "უჯარმა", "Ujarma"),
    V("kesalo", "ქესალო", "Kesalo"),
    V("ksovrisi", "ქსოვრისი", "Ksovrisi"),
    V("giorgitsminda", "გიორგიწმინდა", "Giorgitsminda"),
    V("khashmi", "ხაშმი", "Khashmi"),
    V("japaraantkari", "ჯაფარაანთკარი", "Japaraantkari"),
  ],
  samtredia: [
    V("bashi", "ბაში", "Bashi"),
    V("botseti", "ბოწეთი", "Botseti"),
    V("gomi", "გომი", "Gomi"),
    V("gomismta", "გომისმთა", "Gomismta"),
    V("gormaghali", "გორმაღალი", "Gormaghali"),
    V("gochaijashi", "გოჩაიჯაში", "Gochaijashi"),
    V("dapnari", "დაფნარი", "Dapnari"),
    V("didi-jikhaishi", "დიდი ჯიხაიში", "Didi Jikhaishi"),
    V("ekhvevi", "ეხვევი", "Ekhvevi"),
    V("vazisubani", "ვაზისუბანი", "Vazisubani"),
    V("tavisupleba", "თავისუფლება", "Tavisupleba"),
    V("ianeti", "იანეთი", "Ianeti"),
    V("kulashi", "კულაში", "Kulashi"),
    V("melauri", "მელაური", "Melauri"),
    V("mirotsminda", "მიროწმინდა", "Mirotsminda"),
    V("nabakevi", "ნაბაკევი", "Nabakevi"),
    V("noghaa", "ნოღაა", "Noghaa"),
    V("ochopeti", "ოჩოფეთი", "Ochopeti"),
    V("patara-jikhaishi", "პატარა ჯიხაიში", "Patara Jikhaishi"),
    V("sajavakho", "საჯავახო", "Sajavakho"),
    V("tolebi", "ტოლები", "Tolebi"),
    V("pereta", "ფერეთა", "Pereta"),
    V("kvitiri", "ქვიტირი", "Kvitiri"),
    V("chkhenishi", "ჩხენიში", "Chkhenishi"),
    V("tsiaghubani", "წიაღუბანი", "Tsiaghubani"),
    V("tskepi", "წკეპი", "Tskepi"),
    V("khidistavi", "ხიდისთავი", "Khidistavi"),
  ],
  senaki: [
    V("almati", "ალმათი", "Almati"),
    V("beki", "ბეკი", "Beki"),
    V("gejeti", "გეჯეთი", "Gejeti"),
    V("gora", "გორა", "Gora"),
    V("guma", "გუმა", "Guma"),
    V("eki", "ეკი", "Eki"),
    V("zemo-sorta", "ზემო სორტა", "Zemo Sorta"),
    V("teklati", "თეკლათი", "Teklati"),
    V("kontuati", "კონთუატი", "Kontuati"),
    V("legogie", "ლეგოგიე", "Legogie"),
    V("lesa", "ლესა", "Lesa"),
    V("nosiri", "ნოსირი", "Nosiri"),
    V("otskhao", "ოცხაო", "Otskhao"),
    V("sanka", "სანქა", "Sanka"),
    V("senakispira", "სენაკისპირა", "Senakispira"),
    V("tqiri", "ტყირი", "Tqiri"),
    V("pitskhai", "ფიცხაი", "Pitskhai"),
    V("kolobani", "ქოლობანი", "Kolobani"),
    V("kvemo-sorta", "ქვემო სორტა", "Kvemo Sorta"),
    V("shkhepebi", "შხეფები", "Shkhepebi"),
    V("dzveli-senaki", "ძველი სენაკი", "Dzveli Senaki"),
    V("tsogha", "წოღა", "Tsogha"),
    V("khorshi", "ხორში", "Khorshi"),
  ],
  signagi: [
    V("anaga", "ანაგა", "Anaga"),
    V("arboshiki", "არბოშიკი", "Arboshiki"),
    V("bodbe", "ბოდბე", "Bodbe"),
    V("bodbiskhevi", "ბოდბისხევი", "Bodbiskhevi"),
    V("vakiri", "ვაქირი", "Vakiri"),
    V("jughaani", "ჯუღაანი", "Jughaani"),
    V("zemo-machkhaani", "ზემო მაჩხაანი", "Zemo Machkhaani"),
    V("iliatsminda", "ილიაწმინდა", "Iliatsminda"),
    V("machkhaani", "მაჩხაანი", "Machkhaani"),
    V("nukriani", "ნუკრიანი", "Nukriani"),
    V("sakobo", "საქობო", "Sakobo"),
    V("sighnaghi", "სიღნაღი", "Sighnaghi"),
    V("tibaani", "ტიბაანი", "Tibaani"),
    V("kvemo-machkhaani", "ქვემო მაჩხაანი", "Kvemo Machkhaani"),
    V("qaraaghaji", "ყარააღაჯი", "Qaraaghaji"),
    V("tsnori", "წნორი", "Tsnori"),
  ],
  tkibuli: [
    V("boboti", "ბობოთი", "Boboti"),
    V("gurna", "გურნა", "Gurna"),
    V("damana", "დამანა", "Damana"),
    V("dzadzaleti", "ძაძალეთი", "Dzadzaleti"),
    V("zarani", "ზარანი", "Zarani"),
    V("kursebi", "კურსები", "Kursebi"),
    V("lapekhvava", "ლაფეხვავა", "Lapekhvava"),
    V("mordzgveti", "მორძგვეთი", "Mordzgveti"),
    V("ojola", "ოჯოლა", "Ojola"),
    V("sabue", "საბუე", "Sabue"),
    V("skhvava", "სხვავა", "Skhvava"),
    V("orpiri", "ორპირი", "Orpiri"),
    V("dzbiri", "ძბირი", "Dzbiri"),
    V("tsqaltsitela", "წყალწითელა", "Tsqaltsitela"),
    V("khoji", "ხოჯი", "Khoji"),
  ],
  keda: [
    V("apaneti", "აფანეთი", "Apaneti"),
    V("bzubzu", "ბზუბზუ", "Bzubzu"),
    V("dandalo", "დანდალო", "Dandalo"),
    V("zemo-archeba", "ზემო არჩება", "Zemo Archeba"),
    V("zvare", "ზვარე", "Zvare"),
    V("merisisi", "მერისისი", "Merisisi"),
    V("tskhmorisi", "ცხმორისი", "Tskhmorisi"),
    V("keda", "ქედა", "Keda"),
    V("kveda-archeba", "ქვედა არჩება", "Kveda Archeba"),
    V("dzentsmani", "ძენწმანი", "Dzentsmani"),
    V("chincharauli", "ჭინჭარაული", "Chincharauli"),
    V("kharaula", "ხარაულა", "Kharaula"),
  ],
  kobuleti: [
    V("alambari", "ალამბარი", "Alambari"),
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("boboqveti", "ბობოყვეთი", "Boboqveti"),
    V("gara", "გარა", "Gara"),
    V("gvara", "გვარა", "Gvara"),
    V("grakali", "გრაკალი", "Grakali"),
    V("dirbi", "დირბი", "Dirbi"),
    V("zeniti", "ზენითი", "Zeniti"),
    V("tavisupleba", "თავისუფლება", "Tavisupleba"),
    V("kechieti", "კეჭიეთი", "Kechieti"),
    V("kontripshi", "კონტრიპში", "Kontripshi"),
    V("leghva", "ლეღვა", "Leghva"),
    V("mukhaestate", "მუხაესტატე", "Mukhaestate"),
    V("naomari", "ნაომარი", "Naomari"),
    V("nasakirali", "ნასაკირალი", "Nasakirali"),
    V("patraura", "პატრაურა", "Patraura"),
    V("sachino", "საჩინო", "Sachino"),
    V("skurdi", "სკურდი", "Skurdi"),
    V("potskho", "ფოცხო", "Potskho"),
    V("kakuti", "ქაქუთი", "Kakuti"),
    V("zeda-achqva", "ზედა აჭყვა", "Zeda Achqva"),
    V("kveda-achqva", "ქვედა აჭყვა", "Kveda Achqva"),
    V("kobuleti", "ქობულეთი", "Kobuleti"),
    V("chakvi", "ჩაქვი", "Chakvi"),
    V("tskhramukha", "ცხრამუხა", "Tskhramukha"),
    V("tsqavroka", "წყავროკა", "Tsqavroka"),
    V("khala", "ხალა", "Khala"),
    V("khutsubani", "ხუცუბანი", "Khutsubani"),
  ],
  shuakhevi: [
    V("akhaldaba", "ახალდაბა", "Akhaldaba"),
    V("buturauli", "ბუთურაული", "Buturauli"),
    V("goginauri", "გოგინაური", "Goginauri"),
    V("dacheti", "დაჭეთი", "Dacheti"),
    V("varjanauli", "ვარჯანაული", "Varjanauli"),
    V("zomleti", "ზომლეთი", "Zomleti"),
    V("intskirveti", "ინწკირვეთი", "Intskirveti"),
    V("lomanauri", "ლომანაური", "Lomanauri"),
    V("nigazeuli", "ნიგაზეული", "Nigazeuli"),
    V("okropila", "ოქროპილა", "Okropila"),
    V("paposhvilebi", "პაპოშვილები", "Paposhvilebi"),
    V("takidzeebi", "ტაკიძეები", "Takidzeebi"),
    V("tbeti", "ტბეთი", "Tbeti"),
    V("purtio", "ფურტიო", "Purtio"),
    V("shuakhevi", "შუახევი", "Shuakhevi"),
    V("dzindza", "ძინძა", "Dzindza"),
    V("tsqaltashua", "წყალთაშუა", "Tsqaltashua"),
    V("khichauri", "ხიჭაური", "Khichauri"),
  ],
  chokhatauri: [
    V("amaghleba", "ამაღლება", "Amaghleba"),
    V("bukistsikhe", "ბუკისციხე", "Bukistsikhe"),
    V("gaghma-satsikhuri", "გაღმა საციხური", "Gaghma Satsikhuri"),
    V("gomismta", "გომისმთა", "Gomismta"),
    V("goraberezhouli", "გორაბერეჟოული", "Goraberezhouli"),
    V("dablatsikhe", "დაბლაციხე", "Dablatsikhe"),
    V("erketi", "ერკეთი", "Erketi"),
    V("vaniskedi", "ვანისქედი", "Vaniskedi"),
    V("zoti", "ზოტი", "Zoti"),
    V("tmogvi", "თმოგვი", "Tmogvi"),
    V("ianeti", "იანეთი", "Ianeti"),
    V("kalagoni", "კალაგონი", "Kalagoni"),
    V("kokhnari", "კოხნარი", "Kokhnari"),
    V("metsieti", "მეწიეთი", "Metsieti"),
    V("nabeghlavi", "ნაბეღლავი", "Nabeghlavi"),
    V("satsikhuri", "საციხური", "Satsikhuri"),
    V("surebi", "სურები", "Surebi"),
    V("partskhma", "ფარცხმა", "Partskhma"),
    V("khevisjvari", "ხევისჯვარი", "Khevisjvari"),
    V("khidtavi", "ხიდთავი", "Khidtavi"),
    V("dzimiti", "ძიმითი", "Dzimiti"),
    V("tsirkvali", "წირქვალი", "Tsirkvali"),
  ],
  chokhorotsku: [
    V("akhuti", "ახუთი", "Akhuti"),
    V("zumi", "ზუმი", "Zumi"),
    V("tanashi", "თანაში", "Tanashi"),
    V("kirtskhi", "კირცხი", "Kirtskhi"),
    V("lesichine", "ლესიჭინე", "Lesichine"),
    V("mikeleponi", "მიქელეფონი", "Mikeleponi"),
    V("mukhuri", "მუხური", "Mukhuri"),
    V("napichkhovo", "ნაფიჩხოვო", "Napichkhovo"),
    V("sadaghaio", "სადაღაიო", "Sadaghaio"),
    V("sachino", "საჩინო", "Sachino"),
    V("sarali", "სარალი", "Sarali"),
    V("chalastavi", "ჭალასთავი", "Chalastavi"),
    V("khabume", "ხაბუმე", "Khabume"),
    V("jumiti", "ჯუმითი", "Jumiti"),
  ],
  tsageri: [
    V("alpana", "ალპანა", "Alpana"),
    V("bardnala", "ბარდნალა", "Bardnala"),
    V("gagara", "გაგარა", "Gagara"),
    V("gordi", "გორდი", "Gordi"),
    V("dekhvira", "დეხვირა", "Dekhvira"),
    V("zubi", "ზუბი", "Zubi"),
    V("lajana", "ლაჯანა", "Lajana"),
    V("lechkhumi", "ლეჩხუმი", "Lechkhumi"),
    V("lailashi", "ლაილაში", "Lailashi"),
    V("mukhursha", "მუხურშა", "Mukhursha"),
    V("natspilari", "ნაცპილარი", "Natspilari"),
    V("orbeli", "ორბელი", "Orbeli"),
    V("sairme", "საირმე", "Sairme"),
    V("tvishi", "ტვიში", "Tvishi"),
    V("potskhveri", "ფოცხვერი", "Potskhveri"),
    V("kveda-zubi", "ქვედა ზუბი", "Kveda Zubi"),
    V("tsageri", "ცაგერი", "Tsageri"),
    V("dzveli-sopeli", "ძველი სოფელი", "Dzveli Sopeli"),
    V("chkhuteli", "ჩხუტელი", "Chkhuteli"),
    V("khopuri", "ხოფური", "Khopuri"),
  ],
  tsalenjikha: [
    V("abastumani", "აბასთუმანი", "Abastumani"),
    V("jvari", "ჯვარი", "Jvari"),
    V("etseri", "ეწერი", "Etseri"),
    V("lesa", "ლესა", "Lesa"),
    V("makhoi", "მახოი", "Makhoi"),
    V("mukhuri", "მუხური", "Mukhuri"),
    V("obuji", "ობუჯი", "Obuji"),
    V("papunaeti", "პაპუნაეთი", "Papunaeti"),
    V("sakanela", "საქანელა", "Sakanela"),
    V("taleri", "ტალერი", "Taleri"),
    V("pakhulani", "ფახულანი", "Pakhulani"),
    V("kvemo-sachino", "ქვემო საჩინო", "Kvemo Sachino"),
    V("chkhorotsqu", "ჩხოროწყუ", "Chkhorotsqu"),
    V("tsalenjikha", "წალენჯიხა", "Tsalenjikha"),
    V("chale", "ჭალე", "Chale"),
  ],
  tsalka: [
    V("avrani", "ავრანი", "Avrani"),
    V("aiazma", "აიაზმა", "Aiazma"),
    V("arjevani", "არჯევანი", "Arjevani"),
    V("baraleti", "ბარალეთი", "Baraleti"),
    V("beshtasheni", "ბეშთაშენი", "Beshtasheni"),
    V("gachiani", "გაჩიანი", "Gachiani"),
    V("darakoi", "დარაკოი", "Darakoi"),
    V("didi-sariali", "დიდი სარიალი", "Didi Sariali"),
    V("kavti", "კავთი", "Kavti"),
    V("kartsakhi", "კარწახი", "Kartsakhi"),
    V("koka", "კოკა", "Koka"),
    V("koda", "კოდა", "Koda"),
    V("levani", "ლევანი", "Levani"),
    V("manglisi", "მანგლისი", "Manglisi"),
    V("pataradashtashi", "პატარადაშთაში", "Pataradashtashi"),
    V("santa", "სანთა", "Santa"),
    V("suda", "სუდა", "Suda"),
    V("tabatsquri", "ტაბაწყური", "Tabatsquri"),
    V("tazakendi", "თაზაკენდი", "Tazakendi"),
    V("ktsia", "ქცია", "Ktsia"),
    V("chkhikvta", "ჩხიკვთა", "Chkhikvta"),
    V("tsaghveri", "წაღვერი", "Tsaghveri"),
    V("khachkoi", "ხაჩკოი", "Khachkoi"),
  ],
  tskaltubo: [
    V("agarisjvari", "აგარისჯვარი", "Agarisjvari"),
    V("banoja", "ბანოჯა", "Banoja"),
    V("geguti", "გეგუთი", "Geguti"),
    V("gvimraichala", "გვიმრაიჭალა", "Gvimraichala"),
    V("derchi", "დერჩი", "Derchi"),
    V("zemo-saqvavile", "ზემო საყვავილე", "Zemo Saqvavile"),
    V("zarani", "ზარანი", "Zarani"),
    V("maghlaki", "მაღლაკი", "Maghlaki"),
    V("mepistsqaro", "მეფისწყარო", "Mepistsqaro"),
    V("mukhura", "მუხურა", "Mukhura"),
    V("oputskheti", "ოფუცხეთი", "Oputskheti"),
    V("patara-vani", "პატარა ვანი", "Patara Vani"),
    V("sachkheuri", "საჩხეური", "Sachkheuri"),
    V("saqvavile", "საყვავილე", "Saqvavile"),
    V("sormoni", "სორმონი", "Sormoni"),
    V("partskhanaqanevi", "ფარცხანაყანევი", "Partskhanaqanevi"),
    V("kveda-saqvavile", "ქვედა საყვავილე", "Kveda Saqvavile"),
    V("kvitiri", "ქვიტირი", "Kvitiri"),
    V("qumistavi", "ყუმისტავი", "Qumistavi"),
    V("cholaburi", "ჩოლაბური", "Cholaburi"),
    V("tskhunkuri", "ცხუნკური", "Tskhunkuri"),
    V("tsqaltubo", "წყალტუბო", "Tsqaltubo"),
    V("cholavi", "ჭოლავი", "Cholavi"),
    V("khomuli", "ხომული", "Khomuli"),
  ],
  chiatura: [
    V("bunikauri", "ბუნიკაური", "Bunikauri"),
    V("vake", "ვაკე", "Vake"),
    V("zeda-bereti", "ზედა ბერეთი", "Zeda Bereti"),
    V("zodi", "ზოდი", "Zodi"),
    V("katskhi", "კაცხი", "Katskhi"),
    V("mandaeti", "მანდაეთი", "Mandaeti"),
    V("merevi", "მერევი", "Merevi"),
    V("mghvimevi", "მღვიმევი", "Mghvimevi"),
    V("nasperi", "ნასპერი", "Nasperi"),
    V("perevisa", "პერევისა", "Perevisa"),
    V("sachkhere", "საჩხერე", "Sachkhere"),
    V("savane", "სავანე", "Savane"),
    V("sukureti", "სუქურეთი", "Sukureti"),
    V("tabatsquri", "ტაბაწყური", "Tabatsquri"),
    V("usakhelo", "უსახელო", "Usakhelo"),
    V("kveda-bereti", "ქვედა ბერეთი", "Kveda Bereti"),
    V("kvatsikhe", "ქვაციხე", "Kvatsikhe"),
    V("shukruti", "შუქრუთი", "Shukruti"),
    V("tsirkvali", "წირქვალი", "Tsirkvali"),
    V("chiatura", "ჭიათურა", "Chiatura"),
    V("khreiti", "ხრეითი", "Khreiti"),
  ],
  kharagauli: [
    V("bori", "ბორი", "Bori"),
    V("bzhinevi", "ბჟინევი", "Bzhinevi"),
    V("gedani", "გედანი", "Gedani"),
    V("devza", "დევზა", "Devza"),
    V("vakhani", "ვახანი", "Vakhani"),
    V("zemo-islari", "ზემო ისლარი", "Zemo Islari"),
    V("tetratsqaro", "თეთრაწყარო", "Tetratsqaro"),
    V("katskhi", "კაცხი", "Katskhi"),
    V("lashe", "ლაშე", "Lashe"),
    V("margveti", "მარგვეთი", "Margveti"),
    V("moliti", "მოლითი", "Moliti"),
    V("nunisi", "ნუნისი", "Nunisi"),
    V("patara-vardzia", "პატარა ვარძია", "Patara Vardzia"),
    V("sargveshi", "სარგვეში", "Sargveshi"),
    V("sairme", "საირმე", "Sairme"),
    V("partskhnali", "ფარცხნალი", "Partskhnali"),
    V("chkheri", "ჩხერი", "Chkheri"),
    V("dzirula", "ძირულა", "Dzirula"),
    V("tsipa", "წიფა", "Tsipa"),
    V("kharagauli", "ხარაგაული", "Kharagauli"),
    V("khidi", "ხიდი", "Khidi"),
  ],
  khashuri: [
    V("alisubani", "ალისუბანი", "Alisubani"),
    V("araleti", "არალეთი", "Araleti"),
    V("bebnisi", "ბებნისი", "Bebnisi"),
    V("beki", "ბეკი", "Beki"),
    V("blabana", "ბლაბანა", "Blabana"),
    V("gomi", "გომი", "Gomi"),
    V("gorasavali", "გორასავალი", "Gorasavali"),
    V("guleveti", "გულევეთი", "Guleveti"),
    V("dgvari", "დგვარი", "Dgvari"),
    V("dvaba", "დვაბა", "Dvaba"),
    V("dumatskho", "დუმაცხო", "Dumatskho"),
    V("vaqa", "ვაყა", "Vaqa"),
    V("zroveti", "ზროვეთი", "Zroveti"),
    V("tavtsqaro", "თავწყარო", "Tavtsqaro"),
    V("imdisi", "იმდისი", "Imdisi"),
    V("kldistsqaro", "კლდისწყარო", "Kldistsqaro"),
    V("kodmani", "კოდმანი", "Kodmani"),
    V("koshkebi", "კოშკები", "Koshkebi"),
    V("lashe", "ლაშე", "Lashe"),
    V("mokhisi", "მოხისი", "Mokhisi"),
    V("nabakhtevi", "ნაბახტევი", "Nabakhtevi"),
    V("ozhio", "ოჟიო", "Ozhio"),
    V("pavliani", "პავლიანი", "Pavliani"),
    V("savanisi", "სავანისი", "Savanisi"),
    V("surami", "სურამი", "Surami"),
    V("tashiskari", "ტაშისკარი", "Tashiskari"),
    V("kvishkheti", "ქვიშხეთი", "Kvishkheti"),
    V("tsatskhvi", "ცაცხვი", "Tsatskhvi"),
    V("dzirovani", "ძიროვანი", "Dzirovani"),
    V("tsaghvli", "წაღვლი", "Tsaghvli"),
    V("chorchkha", "ჭორჩხა", "Chorchkha"),
    V("khtsisi", "ხცისი", "Khtsisi"),
  ],
  "khelvachauri-city": [
    V("akhalsheni", "ახალშენი", "Akhalsheni"),
    V("gonio", "გონიო", "Gonio"),
    V("kirnati", "კირნათი", "Kirnati"),
    V("makhinjauri", "მახინჯაური", "Makhinjauri"),
    V("ortabatumi", "ორთაბათუმი", "Ortabatumi"),
    V("petras-tsikhe", "პეტრას ციხე", "Petras Tsikhe"),
    V("salibauri", "სალიბაური", "Salibauri"),
    V("sarpi", "სარფი", "Sarpi"),
    V("kakuti", "ქაქუთი", "Kakuti"),
    V("khelvachauri", "ხელვაჩაური", "Khelvachauri"),
    V("charali", "ჩარალი", "Charali"),
    V("charnali", "ჭარნალი", "Charnali"),
    V("sharabidzeebi", "შარაბიძეები", "Sharabidzeebi"),
  ],
  khobi: [
    V("akhalsopeli", "ახალსოფელი", "Akhalsopeli"),
    V("bia", "ბია", "Bia"),
    V("gurjai", "გურჯაი", "Gurjai"),
    V("didi-tkhinvali", "დიდი თხინვალი", "Didi Tkhinvali"),
    V("dadianeti", "დადიანეთი", "Dadianeti"),
    V("dapnari", "დაფნარი", "Dapnari"),
    V("zemo-kvaloni", "ზემო ქვალონი", "Zemo Kvaloni"),
    V("kirtskhi", "კირცხი", "Kirtskhi"),
    V("kulashi", "კულაში", "Kulashi"),
    V("nojikhevi", "ნოჯიხევი", "Nojikhevi"),
    V("patara-poti", "პატარა ფოთი", "Patara Poti"),
    V("sakvemokedo", "საქვემოქედო", "Sakvemokedo"),
    V("sagvichio", "საგვიჩიო", "Sagvichio"),
    V("kvemo-kvaloni", "ქვემო ქვალონი", "Kvemo Kvaloni"),
    V("kvemo-khorga", "ქვემო ხორგა", "Kvemo Khorga"),
    V("khamiski", "ხამისკი", "Khamiski"),
    V("khobi", "ხობი", "Khobi"),
    V("kheta", "ხეთა", "Kheta"),
    V("chiaura", "ჭიაურა", "Chiaura"),
    V("tsalenjikha", "წალენჯიხა", "Tsalenjikha"),
  ],
  khoni: [
    V("gordi", "გორდი", "Gordi"),
    V("geguti", "გეგუთი", "Geguti"),
    V("dedalki", "დედალქი", "Dedalki"),
    V("zemo-ianeti", "ზემო იანეთი", "Zemo Ianeti"),
    V("kinchkha", "კინჩხა", "Kinchkha"),
    V("matkhoji", "მათხოჯი", "Matkhoji"),
    V("nakhakhulevi", "ნახახულევი", "Nakhakhulevi"),
    V("patara-dzvali", "პატარა ძვალი", "Patara Dzvali"),
    V("sagvarjile", "საგვარჯილე", "Sagvarjile"),
    V("satsulukidzeo", "საწულუკიძეო", "Satsulukidzeo"),
    V("kveda-ianeti", "ქვედა იანეთი", "Kveda Ianeti"),
    V("kutiri", "ქუტირი", "Kutiri"),
    V("khoni", "ხონი", "Khoni"),
    V("dzvali", "ძვალი", "Dzvali"),
  ],
  khulo: [
    V("khulo", "ხულო", "Khulo"),
    V("beshumi", "ბეშუმი", "Beshumi"),
    V("vashlovani", "ვაშლოვანი", "Vashlovani"),
    V("zvare", "ზვარე", "Zvare"),
    V("tagauri", "თაგაური", "Tagauri"),
    V("kvatia", "კვატია", "Kvatia"),
    V("makho", "მახო", "Makho"),
    V("paksadzeebi", "პაქსაძეები", "Paksadzeebi"),
    V("satsikhuri", "საციხური", "Satsikhuri"),
    V("skhalta", "სხალთა", "Skhalta"),
    V("tiaki", "ტიაკი", "Tiaki"),
    V("purtio", "ფურტიო", "Purtio"),
    V("shuasopeli", "შუასოფელი", "Shuasopeli"),
    V("chakhauri", "ჭახაური", "Chakhauri"),
  ],
};

export function getVillagesForMunicipality(
  municipality: string,
): readonly Village[] {
  if (municipality in MUNICIPALITY_VILLAGES) {
    return MUNICIPALITY_VILLAGES[municipality as MunicipalityId];
  }
  return [];
}

export function getVillageLabel(
  villages: readonly Village[],
  id: string,
  locale: "ka" | "en",
): string {
  const village = villages.find((v) => v.id === id);
  if (!village) return id;
  return locale === "ka" ? village.ka : village.en;
}
